// Code generated by avro/gen. DO NOT EDIT.
package deltaflow

type DeltaOp string

const (
	DeltaOpIgnore  DeltaOp = "IGNORE"
	DeltaOpAssert  DeltaOp = "ASSERT"
	DeltaOpRetract DeltaOp = "RETRACT"
	DeltaOpReset   DeltaOp = "RESET"
)
