// Code generated by avro/gen. DO NOT EDIT.
package deltaflow

// GeoPoint is a generated struct.
type GeoPoint struct {
	Lat float64 `avro:"lat" json:"lat" yaml:"Lat"`
	Lon float64 `avro:"lon" json:"lon" yaml:"Lon"`
}

// ScooterUpdate is a generated struct.
type ScooterUpdate struct {
	ActivityState          any `avro:"activity_state" json:"activity_state" yaml:"ActivityState"`
	Pitch                  any `avro:"pitch" json:"pitch" yaml:"Pitch"`
	Roll                   any `avro:"roll" json:"roll" yaml:"Roll"`
	SpeedometerSpeed       any `avro:"speedometer_speed" json:"speedometer_speed" yaml:"SpeedometerSpeed"`
	MotorSpeed             any `avro:"motor_speed" json:"motor_speed" yaml:"MotorSpeed"`
	MotorTemperature       any `avro:"motor_temperature" json:"motor_temperature" yaml:"MotorTemperature"`
	SerialNumber           any `avro:"serial_number" json:"serial_number" yaml:"SerialNumber"`
	AssignedRider          any `avro:"assigned_rider" json:"assigned_rider" yaml:"AssignedRider"`
	ConnectedBatterySerial any `avro:"connected_battery_serial" json:"connected_battery_serial" yaml:"ConnectedBatterySerial"`
	Location               any `avro:"location" json:"location" yaml:"Location"`
}
