// Code generated by avro/gen. DO NOT EDIT.
package deltaflow

// SimpleRecord is a generated struct.
type SimpleRecord struct {
	A int64  `avro:"a" json:"a" yaml:"A"`
	B string `avro:"b" json:"b" yaml:"B"`
}
