// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package relationset

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RelationSetT struct {
	Sid string `json:"sid"`
	St string `json:"st"`
	Si string `json:"si"`
	Dt string `json:"dt"`
	Ts int64 `json:"ts"`
	R []*RelationT `json:"r"`
}

func (t *RelationSetT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	sidOffset := flatbuffers.UOffsetT(0)
	if t.Sid != "" {
		sidOffset = builder.CreateString(t.Sid)
	}
	stOffset := flatbuffers.UOffsetT(0)
	if t.St != "" {
		stOffset = builder.CreateString(t.St)
	}
	siOffset := flatbuffers.UOffsetT(0)
	if t.Si != "" {
		siOffset = builder.CreateString(t.Si)
	}
	dtOffset := flatbuffers.UOffsetT(0)
	if t.Dt != "" {
		dtOffset = builder.CreateString(t.Dt)
	}
	rOffset := flatbuffers.UOffsetT(0)
	if t.R != nil {
		rLength := len(t.R)
		rOffsets := make([]flatbuffers.UOffsetT, rLength)
		for j := 0; j < rLength; j++ {
			rOffsets[j] = t.R[j].Pack(builder)
		}
		RelationSetStartRVector(builder, rLength)
		for j := rLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(rOffsets[j])
		}
		rOffset = builder.EndVector(rLength)
	}
	RelationSetStart(builder)
	RelationSetAddSid(builder, sidOffset)
	RelationSetAddSt(builder, stOffset)
	RelationSetAddSi(builder, siOffset)
	RelationSetAddDt(builder, dtOffset)
	RelationSetAddTs(builder, t.Ts)
	RelationSetAddR(builder, rOffset)
	return RelationSetEnd(builder)
}

func (rcv *RelationSet) UnPackTo(t *RelationSetT) {
	t.Sid = string(rcv.Sid())
	t.St = string(rcv.St())
	t.Si = string(rcv.Si())
	t.Dt = string(rcv.Dt())
	t.Ts = rcv.Ts()
	rLength := rcv.RLength()
	t.R = make([]*RelationT, rLength)
	for j := 0; j < rLength; j++ {
		x := Relation{}
		rcv.R(&x, j)
		t.R[j] = x.UnPack()
	}
}

func (rcv *RelationSet) UnPack() *RelationSetT {
	if rcv == nil {
		return nil
	}
	t := &RelationSetT{}
	rcv.UnPackTo(t)
	return t
}

type RelationSet struct {
	_tab flatbuffers.Table
}

const RelationSetIdentifier = "DTRS"

func GetRootAsRelationSet(buf []byte, offset flatbuffers.UOffsetT) *RelationSet {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RelationSet{}
	x.Init(buf, n+offset)
	return x
}

func FinishRelationSetBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(RelationSetIdentifier)
	builder.FinishWithFileIdentifier(offset, identifierBytes)
}

func RelationSetBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.BufferHasIdentifier(buf, RelationSetIdentifier)
}

func GetSizePrefixedRootAsRelationSet(buf []byte, offset flatbuffers.UOffsetT) *RelationSet {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RelationSet{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRelationSetBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(RelationSetIdentifier)
	builder.FinishSizePrefixedWithFileIdentifier(offset, identifierBytes)
}

func SizePrefixedRelationSetBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.SizePrefixedBufferHasIdentifier(buf, RelationSetIdentifier)
}

func (rcv *RelationSet) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RelationSet) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RelationSet) Sid() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RelationSet) St() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RelationSet) Si() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RelationSet) Dt() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RelationSet) Ts() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RelationSet) MutateTs(n int64) bool {
	return rcv._tab.MutateInt64Slot(12, n)
}

func (rcv *RelationSet) R(obj *Relation, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *RelationSet) RByKey(obj *Relation, key string) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		x := rcv._tab.Vector(o)
		return obj.LookupByKey(key, x, rcv._tab.Bytes)
	}
	return false
}

func (rcv *RelationSet) RLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func RelationSetStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func RelationSetAddSid(builder *flatbuffers.Builder, sid flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(sid), 0)
}
func RelationSetAddSt(builder *flatbuffers.Builder, st flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(st), 0)
}
func RelationSetAddSi(builder *flatbuffers.Builder, si flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(si), 0)
}
func RelationSetAddDt(builder *flatbuffers.Builder, dt flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(dt), 0)
}
func RelationSetAddTs(builder *flatbuffers.Builder, ts int64) {
	builder.PrependInt64Slot(4, ts, 0)
}
func RelationSetAddR(builder *flatbuffers.Builder, r flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(r), 0)
}
func RelationSetStartRVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func RelationSetEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
