// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package relationset

import (
	"bytes"
	flatbuffers "github.com/google/flatbuffers/go"
)

type RelationT struct {
	Di  string `json:"di"`
	Ttl int64  `json:"ttl"`
	Exp int64  `json:"exp"`
}

func (t *RelationT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	diOffset := flatbuffers.UOffsetT(0)
	if t.Di != "" {
		diOffset = builder.CreateString(t.Di)
	}
	RelationStart(builder)
	RelationAddDi(builder, diOffset)
	RelationAddTtl(builder, t.Ttl)
	RelationAddExp(builder, t.Exp)
	return RelationEnd(builder)
}

func (rcv *Relation) UnPackTo(t *RelationT) {
	t.Di = string(rcv.Di())
	t.Ttl = rcv.Ttl()
	t.Exp = rcv.Exp()
}

func (rcv *Relation) UnPack() *RelationT {
	if rcv == nil {
		return nil
	}
	t := &RelationT{}
	rcv.UnPackTo(t)
	return t
}

type Relation struct {
	_tab flatbuffers.Table
}

func GetRootAsRelation(buf []byte, offset flatbuffers.UOffsetT) *Relation {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Relation{}
	x.Init(buf, n+offset)
	return x
}

func FinishRelationBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRelation(buf []byte, offset flatbuffers.UOffsetT) *Relation {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Relation{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRelationBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Relation) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Relation) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Relation) Di() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func RelationKeyCompare(o1, o2 flatbuffers.UOffsetT, buf []byte) bool {
	obj1 := &Relation{}
	obj2 := &Relation{}
	obj1.Init(buf, flatbuffers.UOffsetT(len(buf))-o1)
	obj2.Init(buf, flatbuffers.UOffsetT(len(buf))-o2)
	return string(obj1.Di()) < string(obj2.Di())
}

func (rcv *Relation) LookupByKey(key string, vectorLocation flatbuffers.UOffsetT, buf []byte) bool {
	span := flatbuffers.GetUOffsetT(buf[vectorLocation-4:])
	start := flatbuffers.UOffsetT(0)
	bKey := []byte(key)
	for span != 0 {
		middle := span / 2
		tableOffset := flatbuffers.GetIndirectOffset(buf, vectorLocation+4*(start+middle))
		obj := &Relation{}
		obj.Init(buf, tableOffset)
		comp := bytes.Compare(obj.Di(), bKey)
		if comp > 0 {
			span = middle
		} else if comp < 0 {
			middle += 1
			start += middle
			span -= middle
		} else {
			rcv.Init(buf, tableOffset)
			return true
		}
	}
	return false
}

func (rcv *Relation) Ttl() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Relation) MutateTtl(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func (rcv *Relation) Exp() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Relation) MutateExp(n int64) bool {
	return rcv._tab.MutateInt64Slot(8, n)
}

func RelationStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func RelationAddDi(builder *flatbuffers.Builder, di flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(di), 0)
}
func RelationAddTtl(builder *flatbuffers.Builder, ttl int64) {
	builder.PrependInt64Slot(1, ttl, 0)
}
func RelationAddExp(builder *flatbuffers.Builder, exp int64) {
	builder.PrependInt64Slot(2, exp, 0)
}
func RelationEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
