// Code generated by avro/gen. DO NOT EDIT.
package avrostruct

// GeoPoint is a generated struct.
type GeoPoint struct {
	Lat float64 `avro:"lat" json:"lat" yaml:"Lat"`
	Lon float64 `avro:"lon" json:"lon" yaml:"Lon"`
}

// ActivityStateUpdate is a generated struct.
type ActivityStateUpdate struct {
	Op    string `avro:"op" json:"op" yaml:"Op"`
	Value string `avro:"value" json:"value" yaml:"Value"`
}

// PitchUpdate is a generated struct.
type PitchUpdate struct {
	Op    string  `avro:"op" json:"op" yaml:"Op"`
	Value float32 `avro:"value" json:"value" yaml:"Value"`
}

// RollUpdate is a generated struct.
type RollUpdate struct {
	Op    string  `avro:"op" json:"op" yaml:"Op"`
	Value float32 `avro:"value" json:"value" yaml:"Value"`
}

// SpeedometerSpeedUpdate is a generated struct.
type SpeedometerSpeedUpdate struct {
	Op    string  `avro:"op" json:"op" yaml:"Op"`
	Value float32 `avro:"value" json:"value" yaml:"Value"`
}

// MotorSpeedUpdate is a generated struct.
type MotorSpeedUpdate struct {
	Op    string  `avro:"op" json:"op" yaml:"Op"`
	Value float32 `avro:"value" json:"value" yaml:"Value"`
}

// MotorTemperatureUpdate is a generated struct.
type MotorTemperatureUpdate struct {
	Op    string  `avro:"op" json:"op" yaml:"Op"`
	Value float32 `avro:"value" json:"value" yaml:"Value"`
}

// SerialNumberUpdate is a generated struct.
type SerialNumberUpdate struct {
	Op    string `avro:"op" json:"op" yaml:"Op"`
	Value string `avro:"value" json:"value" yaml:"Value"`
}

// AssignedRiderUpdate is a generated struct.
type AssignedRiderUpdate struct {
	Op    string `avro:"op" json:"op" yaml:"Op"`
	Value string `avro:"value" json:"value" yaml:"Value"`
}

// ConnectedBatterySerialUpdate is a generated struct.
type ConnectedBatterySerialUpdate struct {
	Op    string `avro:"op" json:"op" yaml:"Op"`
	Value string `avro:"value" json:"value" yaml:"Value"`
}

// LocationUpdate is a generated struct.
type LocationUpdate struct {
	Op    string   `avro:"op" json:"op" yaml:"Op"`
	Value GeoPoint `avro:"value" json:"value" yaml:"Value"`
}

// ScooterUpdate is a generated struct.
type ScooterUpdate struct {
	// The unique identifier of the scooter.
	ID string `avro:"id" json:"id" yaml:"Id"`
	// The unique identifier of the transaction.
	TransactionID          string                       `avro:"transaction_id" json:"transaction_id" yaml:"TransactionId"`
	ActivityState          ActivityStateUpdate          `avro:"activity_state" json:"activity_state" yaml:"ActivityState"`
	Pitch                  PitchUpdate                  `avro:"pitch" json:"pitch" yaml:"Pitch"`
	Roll                   RollUpdate                   `avro:"roll" json:"roll" yaml:"Roll"`
	SpeedometerSpeed       SpeedometerSpeedUpdate       `avro:"speedometer_speed" json:"speedometer_speed" yaml:"SpeedometerSpeed"`
	MotorSpeed             MotorSpeedUpdate             `avro:"motor_speed" json:"motor_speed" yaml:"MotorSpeed"`
	MotorTemperature       MotorTemperatureUpdate       `avro:"motor_temperature" json:"motor_temperature" yaml:"MotorTemperature"`
	SerialNumber           SerialNumberUpdate           `avro:"serial_number" json:"serial_number" yaml:"SerialNumber"`
	AssignedRider          AssignedRiderUpdate          `avro:"assigned_rider" json:"assigned_rider" yaml:"AssignedRider"`
	ConnectedBatterySerial ConnectedBatterySerialUpdate `avro:"connected_battery_serial" json:"connected_battery_serial" yaml:"ConnectedBatterySerial"`
	Location               LocationUpdate               `avro:"location" json:"location" yaml:"Location"`
}
