package readergen

import (
	"text/template"

	"go.resystems.io/eddt/internal/arrow/gencommon"
)

// readerTemplateStr is the Go text/template used to generate Arrow readers.
//
// Template structure:
//
//   - Main template ("reader"): Generates per-struct reader struct, New constructor
//     (validate-at-init with column downcast), and LoadRow method.
//   - Sub-template ("loadField"): Emits the per-field load logic inside LoadRow.
//     Only leaf primitives are handled (ValueMethod != "", no containers/structs/marshal/convert).
//
// Design:
//   - Validate-at-init (R5): NewXxxArrowReader performs all type assertions. If a column
//     exists but has the wrong type, it returns an error. Once init succeeds, LoadRow is infallible.
//   - Missing columns (R11/E5): If a column isn't found in the schema, the field stays nil.
//     LoadRow wraps each read in `if col != nil`, so missing columns are silently skipped.
//   - Null handling (R10): For non-pointer value types, IsNull(i) writes the zero-value
//     expression to prevent dirty reads when reusing the output struct.
//   - Column lookup by name (R4): schema.FieldIndices supports arbitrary column ordering.
//   - Read cast uses GoType (not CastType): writer casts GoType->CastType, reader casts back.
const readerTemplateStr = `// Code generated by arrow-reader-gen{{if .Version}} ({{.Version}}){{end}}. DO NOT EDIT.
package {{.PackageName}}

import (
	"fmt"

	"github.com/apache/arrow/go/v18/arrow"
	"github.com/apache/arrow/go/v18/arrow/array"
{{- range .Imports}}
	{{if .Alias}}{{.Alias}} {{end}}"{{.Path}}"
{{- end}}
)
{{range .Structs}}
// {{.Name}}ArrowReader is a strongly-typed Apache Arrow reader for {{.Name}}.
type {{.Name}}ArrowReader struct {
{{- range .Fields}}
{{- template "colField" .}}
{{- end}}
}

// New{{.Name}}ArrowReader creates a new Arrow reader for {{.Name}} from a Record.
// It validates column types at construction time; if a column exists with the wrong
// type, an error is returned. Missing columns are silently skipped during LoadRow.
func New{{.Name}}ArrowReader(rec arrow.Record) (*{{.Name}}ArrowReader, error) {
	r := &{{.Name}}ArrowReader{}
	schema := rec.Schema()
{{- range .Fields}}
{{- template "initField" dict "Field" . "StructName" ""}}
{{- end}}
	return r, nil
}

// LoadRow loads the i-th row from the Arrow record into the output struct.
// Fields whose columns were missing from the record are left untouched.
func (r *{{.Name}}ArrowReader) LoadRow(i int, out *{{.Qualifier}}{{.Name}}) {
{{- range .Fields}}
{{- template "loadField" .}}
{{- end}}
}
{{end}}
{{- define "colField" -}}
{{- if and .ValueMethod (not .IsPointer) (not .IsStruct) (not .IsList) (not .IsMap) (not .IsFixedSizeList) (eq .MarshalMethod "") (eq .ConvertMethod "")}}
	col{{.Name}} {{.ArrowArrayType}}
{{- end}}
{{- end}}

{{- define "initField" -}}
{{- $f := .Field -}}
{{- if and $f.ValueMethod (not $f.IsPointer) (not $f.IsStruct) (not $f.IsList) (not $f.IsMap) (not $f.IsFixedSizeList) (eq $f.MarshalMethod "") (eq $f.ConvertMethod "")}}
	if indices := schema.FieldIndices("{{$f.Name}}"); len(indices) > 0 {
		col, ok := rec.Column(indices[0]).({{$f.ArrowArrayType}})
		if !ok {
			return nil, fmt.Errorf("column %q: expected {{$f.ArrowArrayType}}, got %T", "{{$f.Name}}", rec.Column(indices[0]))
		}
		r.col{{$f.Name}} = col
	}
{{- end}}
{{- end}}

{{- define "loadField" -}}
{{- if and .ValueMethod (not .IsPointer) (not .IsStruct) (not .IsList) (not .IsMap) (not .IsFixedSizeList) (eq .MarshalMethod "") (eq .ConvertMethod "")}}
	if r.col{{.Name}} != nil {
		if r.col{{.Name}}.IsNull(i) {
			out.{{.Name}} = {{.ZeroExpr}}
		} else {
			out.{{.Name}} = {{.GoType}}(r.col{{.Name}}.Value(i))
		}
	}
{{- end}}
{{- end}}
`

var readerTemplate = template.Must(template.New("reader").Funcs(template.FuncMap{
	"dict": func(values ...any) map[string]any {
		m := make(map[string]any)
		for i := 0; i < len(values); i += 2 {
			m[values[i].(string)] = values[i+1]
		}
		return m
	},
	"stripPtr": func(s string) string {
		if len(s) > 0 && s[0] == '*' {
			return s[1:]
		}
		return s
	},
}).Parse(readerTemplateStr))

type templateData struct {
	PackageName string
	Version     string
	Imports     []gencommon.ImportInfo
	Structs     []gencommon.StructInfo
}
