package readergen

import (
	"strings"
	"text/template"

	"go.resystems.io/eddt/internal/arrow/gencommon"
)

// readerTemplateStr is the Go text/template used to generate Arrow readers.
//
// Template structure:
//
//   - Main template ("reader"): Generates per-struct reader struct, New constructor
//     (validate-at-init with column downcast), and LoadRow method.
//   - Sub-template ("loadField"): Emits the per-field load logic inside LoadRow.
//     Leaf primitives and pointer-to-primitives are handled (ValueMethod != "",
//     no containers/structs/marshal/convert). Pointer fields use null→nil semantics
//     and dereference-assign for zero-allocation reuse.
//
// Design:
//   - Validate-at-init (R5): NewXxxArrowReader performs all type assertions. If a column
//     exists but has the wrong type, it returns an error. Once init succeeds, LoadRow is infallible.
//   - Missing columns (R11/E5): If a column isn't found in the schema, the field stays nil.
//     LoadRow wraps each read in `if col != nil`, so missing columns are silently skipped.
//   - Null handling (R10): For non-pointer value types, IsNull(i) writes the zero-value
//     expression to prevent dirty reads when reusing the output struct.
//   - Column lookup by name (R4): schema.FieldIndices supports arbitrary column ordering.
//   - Read cast uses GoType (not CastType): writer casts GoType->CastType, reader casts back.
const readerTemplateStr = `// Code generated by arrow-reader-gen{{if .Version}} ({{.Version}}){{end}}. DO NOT EDIT.
package {{.PackageName}}

import (
	"fmt"

	"github.com/apache/arrow/go/v18/arrow"
	"github.com/apache/arrow/go/v18/arrow/array"
{{- range .Imports}}
	{{if .Alias}}{{.Alias}} {{end}}"{{.Path}}"
{{- end}}
)
{{range .Structs}}
// {{.Name}}ArrowReader is a strongly-typed Apache Arrow reader for {{.Name}}.
type {{.Name}}ArrowReader struct {
{{- range .Fields}}
{{- template "colField" .}}
{{- end}}
}

// New{{.Name}}ArrowReader creates a new Arrow reader for {{.Name}} from a Record.
// It validates column types at construction time; if a column exists with the wrong
// type, an error is returned. Missing columns are silently skipped during LoadRow.
func New{{.Name}}ArrowReader(rec arrow.Record) (*{{.Name}}ArrowReader, error) {
	r := &{{.Name}}ArrowReader{}
	schema := rec.Schema()
{{- range .Fields}}
{{- template "initField" dict "Field" . "StructName" ""}}
{{- end}}
	return r, nil
}

func new{{.Name}}ArrowReaderFromStruct(col *array.Struct) (*{{.Name}}ArrowReader, error) {
	r := &{{.Name}}ArrowReader{}
	dt := col.DataType().(*arrow.StructType)
	_ = dt
	_ = col
{{- range .Fields}}
{{- template "initStructField" dict "Field" .}}
{{- end}}
	return r, nil
}

// LoadRow loads the i-th row from the Arrow record into the output struct.
// Fields whose columns were missing from the record are left untouched.
func (r *{{.Name}}ArrowReader) LoadRow(i int, out *{{.Qualifier}}{{.Name}}) {
{{- range .Fields}}
{{- template "loadField" .}}
{{- end}}
}
{{end}}
{{- define "colField" -}}
{{- if .IsStruct}}
	col{{.Name}} {{.ArrowArrayType}}
	reader{{.Name}} *{{.StructName}}ArrowReader
{{- else if and .IsMap (not .IsPointer)}}
{{- template "colFieldMap" dict "Name" .Name "Info" . "Depth" 0}}
{{- else if and (or .IsList .IsFixedSizeList) (not .IsPointer)}}
{{- template "colFieldList" dict "Name" .Name "Info" . "Depth" 0}}
{{- else if and .ValueMethod (not .IsStruct) (not .IsList) (not .IsMap) (not .IsFixedSizeList) (eq .MarshalMethod "")}}
	col{{.Name}} {{.ArrowArrayType}}
{{- end}}
{{- end}}

{{- define "colFieldMap" -}}
{{- $name := .Name -}}
{{- $info := .Info -}}
{{- $d := .Depth -}}
{{- $prefix := printf "%s%s" $name (repeat "Items" $d)}}
	col{{$prefix}} {{$info.ArrowArrayType}}
	col{{$prefix}}Keys {{$info.KeyInfo.ArrowArrayType}}
{{- if $info.EltInfo.IsMap}}
{{- template "colFieldMap" dict "Name" $name "Info" $info.EltInfo "Depth" (add $d 1)}}
{{- else if $info.EltInfo.IsStruct}}
	col{{$prefix}}Items {{$info.EltInfo.ArrowArrayType}}
	reader{{$prefix}}Items *{{$info.EltInfo.StructName}}ArrowReader
{{- else if or $info.EltInfo.IsList $info.EltInfo.IsFixedSizeList}}
{{- template "colFieldList" dict "Name" (printf "%sItems" $prefix) "Info" $info.EltInfo "Depth" 0}}
{{- else}}
	col{{$prefix}}Items {{$info.EltInfo.ArrowArrayType}}
{{- end}}
{{- end}}

{{- define "colFieldList" -}}
{{- $name := .Name -}}
{{- $info := .Info -}}
{{- $d := .Depth}}
	col{{$name}}{{repeat "Elts" $d}} {{$info.ArrowArrayType}}
{{- if $info.EltInfo.IsStruct}}
	col{{$name}}{{repeat "Elts" (add $d 1)}} {{$info.EltInfo.ArrowArrayType}}
	reader{{$name}}{{repeat "Elts" (add $d 1)}} *{{$info.EltInfo.StructName}}ArrowReader
{{- else if or $info.EltInfo.IsList $info.EltInfo.IsFixedSizeList}}
{{- template "colFieldList" dict "Name" $name "Info" $info.EltInfo "Depth" (add $d 1)}}
{{- else}}
	col{{$name}}{{repeat "Elts" (add $d 1)}} {{$info.EltInfo.ArrowArrayType}}
{{- end}}
{{- end}}

{{- define "initField" -}}
{{- $f := .Field -}}
{{- if $f.IsStruct}}
	if indices := schema.FieldIndices("{{$f.Name}}"); len(indices) > 0 {
		col, ok := rec.Column(indices[0]).({{$f.ArrowArrayType}})
		if !ok {
			return nil, fmt.Errorf("column %q: expected {{$f.ArrowArrayType}}, got %T", "{{$f.Name}}", rec.Column(indices[0]))
		}
		r.col{{$f.Name}} = col
		{
			var err error
			r.reader{{$f.Name}}, err = new{{$f.StructName}}ArrowReaderFromStruct(col)
			if err != nil {
				return nil, err
			}
		}
	}
{{- else if and $f.IsMap (not $f.IsPointer)}}
{{- template "initFieldMap" dict "Name" $f.Name "Info" $f}}
{{- else if and (or $f.IsList $f.IsFixedSizeList) (not $f.IsPointer)}}
{{- template "initFieldList" dict "Name" $f.Name "Info" $f}}
{{- else if and $f.ValueMethod (not $f.IsStruct) (not $f.IsList) (not $f.IsMap) (not $f.IsFixedSizeList) (eq $f.MarshalMethod "")}}
	if indices := schema.FieldIndices("{{$f.Name}}"); len(indices) > 0 {
		col, ok := rec.Column(indices[0]).({{$f.ArrowArrayType}})
		if !ok {
			return nil, fmt.Errorf("column %q: expected {{$f.ArrowArrayType}}, got %T", "{{$f.Name}}", rec.Column(indices[0]))
		}
		r.col{{$f.Name}} = col
	}
{{- end}}
{{- end}}

{{- define "initFieldMap" -}}
{{- $name := .Name -}}
{{- $info := .Info}}
	if indices := schema.FieldIndices("{{$name}}"); len(indices) > 0 {
		col, ok := rec.Column(indices[0]).({{$info.ArrowArrayType}})
		if !ok {
			return nil, fmt.Errorf("column %q: expected {{$info.ArrowArrayType}}, got %T", "{{$name}}", rec.Column(indices[0]))
		}
		r.col{{$name}} = col
{{- template "initFieldMapChild" dict "Name" $name "Info" $info "Depth" 0}}
	}
{{- end}}

{{- define "initFieldMapChild" -}}
{{- $name := .Name -}}
{{- $info := .Info -}}
{{- $d := .Depth -}}
{{- $prefix := printf "%s%s" $name (repeat "Items" $d) -}}
{{- $parentCol := printf "r.col%s" $prefix}}
		{
			keys, ok := {{$parentCol}}.Keys().({{$info.KeyInfo.ArrowArrayType}})
			if !ok {
				return nil, fmt.Errorf("column %q keys: expected {{$info.KeyInfo.ArrowArrayType}}, got %T", "{{$name}}", {{$parentCol}}.Keys())
			}
			r.col{{$prefix}}Keys = keys
		}
{{- if $info.EltInfo.IsMap}}
		{
			items, ok := {{$parentCol}}.Items().({{$info.EltInfo.ArrowArrayType}})
			if !ok {
				return nil, fmt.Errorf("column %q items: expected {{$info.EltInfo.ArrowArrayType}}, got %T", "{{$name}}", {{$parentCol}}.Items())
			}
			r.col{{$name}}{{repeat "Items" (add $d 1)}} = items
		}
{{- template "initFieldMapChild" dict "Name" $name "Info" $info.EltInfo "Depth" (add $d 1)}}
{{- else if $info.EltInfo.IsStruct}}
		{
			items, ok := {{$parentCol}}.Items().({{$info.EltInfo.ArrowArrayType}})
			if !ok {
				return nil, fmt.Errorf("column %q items: expected {{$info.EltInfo.ArrowArrayType}}, got %T", "{{$name}}", {{$parentCol}}.Items())
			}
			r.col{{$prefix}}Items = items
			var err error
			r.reader{{$prefix}}Items, err = new{{$info.EltInfo.StructName}}ArrowReaderFromStruct(items)
			if err != nil {
				return nil, err
			}
		}
{{- else if or $info.EltInfo.IsList $info.EltInfo.IsFixedSizeList}}
		{
			items, ok := {{$parentCol}}.Items().({{$info.EltInfo.ArrowArrayType}})
			if !ok {
				return nil, fmt.Errorf("column %q items: expected {{$info.EltInfo.ArrowArrayType}}, got %T", "{{$name}}", {{$parentCol}}.Items())
			}
			r.col{{$prefix}}Items = items
{{- template "initFieldListChild" dict "Name" (printf "%sItems" $prefix) "Info" $info.EltInfo "Depth" 0}}
		}
{{- else}}
		{
			items, ok := {{$parentCol}}.Items().({{$info.EltInfo.ArrowArrayType}})
			if !ok {
				return nil, fmt.Errorf("column %q items: expected {{$info.EltInfo.ArrowArrayType}}, got %T", "{{$name}}", {{$parentCol}}.Items())
			}
			r.col{{$prefix}}Items = items
		}
{{- end}}
{{- end}}

{{- define "initFieldList" -}}
{{- $name := .Name -}}
{{- $info := .Info}}
	if indices := schema.FieldIndices("{{$name}}"); len(indices) > 0 {
		col, ok := rec.Column(indices[0]).({{$info.ArrowArrayType}})
		if !ok {
			return nil, fmt.Errorf("column %q: expected {{$info.ArrowArrayType}}, got %T", "{{$name}}", rec.Column(indices[0]))
		}
		r.col{{$name}} = col
{{- template "initFieldListChild" dict "Name" $name "Info" $info "Depth" 0}}
	}
{{- end}}

{{- define "initFieldListChild" -}}
{{- $name := .Name -}}
{{- $info := .Info -}}
{{- $d := .Depth -}}
{{- $parentCol := printf "r.col%s%s" $name (repeat "Elts" $d) -}}
{{- $childCol := printf "r.col%s%s" $name (repeat "Elts" (add $d 1)) -}}
{{- $childType := $info.EltInfo.ArrowArrayType -}}
{{- if $info.EltInfo.IsStruct}}
		{
			elts, ok := {{$parentCol}}.ListValues().({{$childType}})
			if !ok {
				return nil, fmt.Errorf("column %q child: expected {{$childType}}, got %T", "{{$name}}", {{$parentCol}}.ListValues())
			}
			{{$childCol}} = elts
			var err error
			r.reader{{$name}}{{repeat "Elts" (add $d 1)}}, err = new{{$info.EltInfo.StructName}}ArrowReaderFromStruct(elts)
			if err != nil {
				return nil, err
			}
		}
{{- else if or $info.EltInfo.IsList $info.EltInfo.IsFixedSizeList}}
		{
			elts, ok := {{$parentCol}}.ListValues().({{$childType}})
			if !ok {
				return nil, fmt.Errorf("column %q child: expected {{$childType}}, got %T", "{{$name}}", {{$parentCol}}.ListValues())
			}
			{{$childCol}} = elts
{{- template "initFieldListChild" dict "Name" $name "Info" $info.EltInfo "Depth" (add $d 1)}}
		}
{{- else}}
		{
			elts, ok := {{$parentCol}}.ListValues().({{$childType}})
			if !ok {
				return nil, fmt.Errorf("column %q child: expected {{$childType}}, got %T", "{{$name}}", {{$parentCol}}.ListValues())
			}
			{{$childCol}} = elts
		}
{{- end}}
{{- end}}

{{- define "initStructField" -}}
{{- $f := .Field -}}
{{- if $f.IsStruct}}
	if idx, ok := dt.FieldIdx("{{$f.Name}}"); ok {
		child, ok := col.Field(idx).({{$f.ArrowArrayType}})
		if !ok {
			return nil, fmt.Errorf("struct field %q: expected {{$f.ArrowArrayType}}, got %T", "{{$f.Name}}", col.Field(idx))
		}
		r.col{{$f.Name}} = child
		{
			var err error
			r.reader{{$f.Name}}, err = new{{$f.StructName}}ArrowReaderFromStruct(child)
			if err != nil {
				return nil, err
			}
		}
	}
{{- else if and $f.IsMap (not $f.IsPointer)}}
	if idx, ok := dt.FieldIdx("{{$f.Name}}"); ok {
		child, ok := col.Field(idx).({{$f.ArrowArrayType}})
		if !ok {
			return nil, fmt.Errorf("struct field %q: expected {{$f.ArrowArrayType}}, got %T", "{{$f.Name}}", col.Field(idx))
		}
		r.col{{$f.Name}} = child
{{- template "initFieldMapChild" dict "Name" $f.Name "Info" $f "Depth" 0}}
	}
{{- else if and (or $f.IsList $f.IsFixedSizeList) (not $f.IsPointer)}}
	if idx, ok := dt.FieldIdx("{{$f.Name}}"); ok {
		child, ok := col.Field(idx).({{$f.ArrowArrayType}})
		if !ok {
			return nil, fmt.Errorf("struct field %q: expected {{$f.ArrowArrayType}}, got %T", "{{$f.Name}}", col.Field(idx))
		}
		r.col{{$f.Name}} = child
{{- template "initFieldListChild" dict "Name" $f.Name "Info" $f "Depth" 0}}
	}
{{- else if and $f.ValueMethod (not $f.IsStruct) (not $f.IsList) (not $f.IsMap) (not $f.IsFixedSizeList) (eq $f.MarshalMethod "")}}
	if idx, ok := dt.FieldIdx("{{$f.Name}}"); ok {
		child, ok := col.Field(idx).({{$f.ArrowArrayType}})
		if !ok {
			return nil, fmt.Errorf("struct field %q: expected {{$f.ArrowArrayType}}, got %T", "{{$f.Name}}", col.Field(idx))
		}
		r.col{{$f.Name}} = child
	}
{{- end}}
{{- end}}

{{- define "loadField" -}}
{{- if and .IsStruct (not .IsPointer)}}
	if r.col{{.Name}} != nil {
		if r.col{{.Name}}.IsNull(i) {
			out.{{.Name}} = {{.StructQualifier}}{{.StructName}}{}
		} else {
			r.reader{{.Name}}.LoadRow(i, &out.{{.Name}})
		}
	}
{{- else if and .IsStruct .IsPointer}}
	if r.col{{.Name}} != nil {
		if r.col{{.Name}}.IsNull(i) {
			out.{{.Name}} = nil
		} else {
			if out.{{.Name}} == nil {
				out.{{.Name}} = &{{.StructQualifier}}{{.StructName}}{}
			}
			r.reader{{.Name}}.LoadRow(i, out.{{.Name}})
		}
	}
{{- else if and .IsMap (not .IsPointer)}}
{{- template "loadFieldMap" dict "Name" .Name "Info" . "Target" (printf "out.%s" .Name)}}
{{- else if and .IsList (not .IsPointer)}}
{{- template "loadFieldList" dict "Name" .Name "Info" . "Target" (printf "out.%s" .Name)}}
{{- else if and .IsFixedSizeList (not .IsPointer)}}
{{- template "loadFieldFixedList" dict "Name" .Name "Info" . "Target" (printf "out.%s" .Name)}}
{{- else if and .ValueMethod (not .IsPointer) (not .IsStruct) (not .IsList) (not .IsMap) (not .IsFixedSizeList) (eq .MarshalMethod "")}}
	if r.col{{.Name}} != nil {
		if r.col{{.Name}}.IsNull(i) {
			out.{{.Name}} = {{.ZeroExpr}}
		} else {
{{- if .ConvertBackExpr}}
{{- if .ConvertBackIsPtr}}
			out.{{.Name}} = *{{printf .ConvertBackExpr (printf "r.col%s.Value(i)" .Name)}}
{{- else}}
			out.{{.Name}} = {{printf .ConvertBackExpr (printf "r.col%s.Value(i)" .Name)}}
{{- end}}
{{- else}}
			out.{{.Name}} = {{.GoType}}(r.col{{.Name}}.Value(i))
{{- end}}
		}
	}
{{- end}}
{{- if and .ValueMethod .IsPointer (not .IsStruct) (not .IsList) (not .IsMap) (not .IsFixedSizeList) (eq .MarshalMethod "")}}
	if r.col{{.Name}} != nil {
		if r.col{{.Name}}.IsNull(i) {
			out.{{.Name}} = nil
{{- if and .ConvertBackExpr .ConvertBackIsPtr}}
		} else {
			out.{{.Name}} = {{printf .ConvertBackExpr (printf "r.col%s.Value(i)" .Name)}}
		}
{{- else if .ConvertBackExpr}}
		} else if out.{{.Name}} == nil {
			v := {{printf .ConvertBackExpr (printf "r.col%s.Value(i)" .Name)}}
			out.{{.Name}} = &v
		} else {
			*out.{{.Name}} = {{printf .ConvertBackExpr (printf "r.col%s.Value(i)" .Name)}}
		}
{{- else}}
		} else if out.{{.Name}} == nil {
			v := {{stripPtr .GoType}}(r.col{{.Name}}.Value(i))
			out.{{.Name}} = &v
		} else {
			*out.{{.Name}} = {{stripPtr .GoType}}(r.col{{.Name}}.Value(i))
		}
{{- end}}
	}
{{- end}}
{{- end}}

{{- define "loadFieldList" -}}
{{- $name := .Name -}}
{{- $info := .Info -}}
{{- $target := .Target}}
	if r.col{{$name}} != nil {
		if r.col{{$name}}.IsNull(i) {
			{{$target}} = nil
		} else {
{{- template "loadFieldListInner" dict "Name" $name "Info" $info "Target" $target "Depth" 0 "IdxExpr" "i"}}
		}
	}
{{- end}}

{{- define "loadFieldListInner" -}}
{{- $name := .Name -}}
{{- $info := .Info -}}
{{- $target := .Target -}}
{{- $d := .Depth -}}
{{- $idx := .IdxExpr -}}
{{- $colName := printf "r.col%s%s" $name (repeat "Elts" $d) -}}
{{- $childCol := printf "r.col%s%s" $name (repeat "Elts" (add $d 1)) -}}
{{- $s := printf "s%d" $d -}}
{{- $e := printf "e%d" $d -}}
{{- $n := printf "n%d" $d -}}
{{- $j := printf "j%d" $d}}
			{{$s}}, {{$e}} := {{$colName}}.ValueOffsets({{$idx}})
			{{$n}} := int({{$e}} - {{$s}})
			if {{$n}} > 0 && cap({{$target}}) >= {{$n}} {
				{{$target}} = {{$target}}[:{{$n}}]
			} else {
				{{$target}} = make({{$info.GoType}}, {{$n}})
			}
			for {{$j}} := 0; {{$j}} < {{$n}}; {{$j}}++ {
{{- if $info.EltInfo.IsStruct}}
				idx{{$d}} := int({{$s}}) + {{$j}}
				if {{$childCol}}.IsNull(idx{{$d}}) {
					{{$target}}[{{$j}}] = {{$info.EltInfo.StructQualifier}}{{$info.EltInfo.StructName}}{}
				} else {
					r.reader{{$name}}{{repeat "Elts" (add $d 1)}}.LoadRow(idx{{$d}}, &{{$target}}[{{$j}}])
				}
{{- else if $info.EltInfo.IsList}}
				idx{{$d}} := int({{$s}}) + {{$j}}
				if {{$childCol}}.IsNull(idx{{$d}}) {
					{{$target}}[{{$j}}] = nil
				} else {
{{- template "loadFieldListInner" dict "Name" $name "Info" $info.EltInfo "Target" (printf "%s[%s]" $target $j) "Depth" (add $d 1) "IdxExpr" (printf "idx%d" $d)}}
				}
{{- else if $info.EltInfo.IsFixedSizeList}}
				idx{{$d}} := int({{$s}}) + {{$j}}
{{- template "loadFieldFixedListInner" dict "Name" $name "Info" $info.EltInfo "Target" (printf "%s[%s]" $target $j) "Depth" (add $d 1) "IdxExpr" (printf "idx%d" $d)}}
{{- else}}
{{- if $info.EltInfo.ConvertBackExpr}}
{{- if $info.EltInfo.ConvertBackIsPtr}}
				{{$target}}[{{$j}}] = *{{printf $info.EltInfo.ConvertBackExpr (printf "%s.Value(int(%s) + %s)" $childCol $s $j)}}
{{- else}}
				{{$target}}[{{$j}}] = {{printf $info.EltInfo.ConvertBackExpr (printf "%s.Value(int(%s) + %s)" $childCol $s $j)}}
{{- end}}
{{- else}}
				{{$target}}[{{$j}}] = {{$info.EltInfo.GoType}}({{$childCol}}.Value(int({{$s}}) + {{$j}}))
{{- end}}
{{- end}}
			}
{{- end}}

{{- define "loadFieldFixedList" -}}
{{- $name := .Name -}}
{{- $info := .Info -}}
{{- $target := .Target}}
	if r.col{{$name}} != nil {
		if r.col{{$name}}.IsNull(i) {
			{{$target}} = {{$info.ZeroExpr}}
		} else {
{{- template "loadFieldFixedListInner" dict "Name" $name "Info" $info "Target" $target "Depth" 0 "IdxExpr" "i"}}
		}
	}
{{- end}}

{{- define "loadFieldFixedListInner" -}}
{{- $name := .Name -}}
{{- $info := .Info -}}
{{- $target := .Target -}}
{{- $d := .Depth -}}
{{- $idx := .IdxExpr -}}
{{- $colName := printf "r.col%s%s" $name (repeat "Elts" $d) -}}
{{- $childCol := printf "r.col%s%s" $name (repeat "Elts" (add $d 1)) -}}
{{- $s := printf "s%d" $d -}}
{{- $j := printf "j%d" $d}}
			{{$s}}, _ := {{$colName}}.ValueOffsets({{$idx}})
			for {{$j}} := 0; {{$j}} < {{$info.FixedSizeLen}}; {{$j}}++ {
{{- if $info.EltInfo.IsStruct}}
				idx{{$d}} := int({{$s}}) + {{$j}}
				if {{$childCol}}.IsNull(idx{{$d}}) {
					{{$target}}[{{$j}}] = {{$info.EltInfo.StructQualifier}}{{$info.EltInfo.StructName}}{}
				} else {
					r.reader{{$name}}{{repeat "Elts" (add $d 1)}}.LoadRow(idx{{$d}}, &{{$target}}[{{$j}}])
				}
{{- else if $info.EltInfo.IsFixedSizeList}}
				idx{{$d}} := int({{$s}}) + {{$j}}
{{- template "loadFieldFixedListInner" dict "Name" $name "Info" $info.EltInfo "Target" (printf "%s[%s]" $target $j) "Depth" (add $d 1) "IdxExpr" (printf "idx%d" $d)}}
{{- else if $info.EltInfo.IsList}}
				idx{{$d}} := int({{$s}}) + {{$j}}
				if {{$childCol}}.IsNull(idx{{$d}}) {
					{{$target}}[{{$j}}] = nil
				} else {
{{- template "loadFieldListInner" dict "Name" $name "Info" $info.EltInfo "Target" (printf "%s[%s]" $target $j) "Depth" (add $d 1) "IdxExpr" (printf "idx%d" $d)}}
				}
{{- else}}
{{- if $info.EltInfo.ConvertBackExpr}}
{{- if $info.EltInfo.ConvertBackIsPtr}}
				{{$target}}[{{$j}}] = *{{printf $info.EltInfo.ConvertBackExpr (printf "%s.Value(int(%s) + %s)" $childCol $s $j)}}
{{- else}}
				{{$target}}[{{$j}}] = {{printf $info.EltInfo.ConvertBackExpr (printf "%s.Value(int(%s) + %s)" $childCol $s $j)}}
{{- end}}
{{- else}}
				{{$target}}[{{$j}}] = {{$info.EltInfo.GoType}}({{$childCol}}.Value(int({{$s}}) + {{$j}}))
{{- end}}
{{- end}}
			}
{{- end}}

{{- define "loadFieldMap" -}}
{{- $name := .Name -}}
{{- $info := .Info -}}
{{- $target := .Target}}
	if r.col{{$name}} != nil {
		if r.col{{$name}}.IsNull(i) {
			{{$target}} = nil
		} else {
{{- template "loadFieldMapInner" dict "Name" $name "Info" $info "Target" $target "Depth" 0 "IdxExpr" "i"}}
		}
	}
{{- end}}

{{- define "loadFieldMapInner" -}}
{{- $name := .Name -}}
{{- $info := .Info -}}
{{- $target := .Target -}}
{{- $d := .Depth -}}
{{- $idx := .IdxExpr -}}
{{- $prefix := printf "%s%s" $name (repeat "Items" $d) -}}
{{- $colName := printf "r.col%s" $prefix -}}
{{- $keysCol := printf "r.col%sKeys" $prefix -}}
{{- $s := printf "s%d" $d -}}
{{- $e := printf "e%d" $d -}}
{{- $n := printf "n%d" $d -}}
{{- $j := printf "j%d" $d -}}
{{- $k := printf "k%d" $d}}
			{{$s}}, {{$e}} := {{$colName}}.ValueOffsets({{$idx}})
			{{$n}} := int({{$e}} - {{$s}})
			if {{$target}} == nil {
				{{$target}} = make({{$info.GoType}}, {{$n}})
			} else {
				clear({{$target}})
			}
			for {{$j}} := 0; {{$j}} < {{$n}}; {{$j}}++ {
				{{$k}} := {{$info.KeyInfo.GoType}}({{$keysCol}}.Value(int({{$s}}) + {{$j}}))
{{- if $info.EltInfo.IsStruct}}
				midx{{$d}} := int({{$s}}) + {{$j}}
				var sv{{$d}} {{$info.EltInfo.StructQualifier}}{{$info.EltInfo.StructName}}
				if !r.col{{$prefix}}Items.IsNull(midx{{$d}}) {
					r.reader{{$prefix}}Items.LoadRow(midx{{$d}}, &sv{{$d}})
				}
				{{$target}}[{{$k}}] = sv{{$d}}
{{- else if $info.EltInfo.IsMap}}
				midx{{$d}} := int({{$s}}) + {{$j}}
				if r.col{{$name}}{{repeat "Items" (add $d 1)}}.IsNull(midx{{$d}}) {
					{{$target}}[{{$k}}] = nil
				} else {
{{- template "loadFieldMapInner" dict "Name" $name "Info" $info.EltInfo "Target" (printf "%s[%s]" $target $k) "Depth" (add $d 1) "IdxExpr" (printf "midx%d" $d)}}
				}
{{- else if $info.EltInfo.IsList}}
				midx{{$d}} := int({{$s}}) + {{$j}}
				if r.col{{$prefix}}Items.IsNull(midx{{$d}}) {
					{{$target}}[{{$k}}] = nil
				} else {
{{- template "loadFieldListInner" dict "Name" (printf "%sItems" $prefix) "Info" $info.EltInfo "Target" (printf "%s[%s]" $target $k) "Depth" 0 "IdxExpr" (printf "midx%d" $d)}}
				}
{{- else}}
{{- if $info.EltInfo.ConvertBackExpr}}
{{- if $info.EltInfo.ConvertBackIsPtr}}
				{{$target}}[{{$k}}] = *{{printf $info.EltInfo.ConvertBackExpr (printf "r.col%sItems.Value(int(%s) + %s)" $prefix $s $j)}}
{{- else}}
				{{$target}}[{{$k}}] = {{printf $info.EltInfo.ConvertBackExpr (printf "r.col%sItems.Value(int(%s) + %s)" $prefix $s $j)}}
{{- end}}
{{- else}}
				{{$target}}[{{$k}}] = {{$info.EltInfo.GoType}}(r.col{{$prefix}}Items.Value(int({{$s}}) + {{$j}}))
{{- end}}
{{- end}}
			}
{{- end}}
`

var readerTemplate = template.Must(template.New("reader").Funcs(template.FuncMap{
	"dict": func(values ...any) map[string]any {
		m := make(map[string]any)
		for i := 0; i < len(values); i += 2 {
			m[values[i].(string)] = values[i+1]
		}
		return m
	},
	"stripPtr": func(s string) string {
		if len(s) > 0 && s[0] == '*' {
			return s[1:]
		}
		return s
	},
	"lowerFirst": func(s string) string {
		if len(s) == 0 {
			return s
		}
		return strings.ToLower(s[:1]) + s[1:]
	},
	"add":    func(a, b int) int { return a + b },
	"repeat": func(s string, n int) string { return strings.Repeat(s, n) },
}).Parse(readerTemplateStr))

type templateData struct {
	PackageName string
	Version     string
	Imports     []gencommon.ImportInfo
	Structs     []gencommon.StructInfo
}
