package writergen

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
	"text/template"
)

// writerTemplateStr is the Go text/template used to generate Arrow append writers.
//
// Template structure:
//
//   - Main template ("writer"): Generates the public API per struct — schema constructor,
//     ArrowWriter struct, New/Release/Append/NewRecord methods, and the AppendStruct helper.
//   - Sub-template ("appendFields"): Shared field-handling logic used by both the Append
//     method (which accesses builders via w.b.Field) and AppendStruct (via b.FieldBuilder).
//     The builder accessor is passed as the "Bldr" key in a dict.
//
// A "dict" FuncMap helper is registered to pass multiple named values to sub-templates,
// since Go's text/template only supports a single pipeline argument to {{template}}.
//
// Template data is provided via the templateData struct. When the output package differs
// from the input package(s), Imports is populated with the required import paths and aliases,
// causing the template to emit import statements and qualify struct type references with the
// appropriate package qualifier (stored on each StructInfo as Qualifier).
const writerTemplateStr = `// Code generated by arrow-writer-gen. DO NOT EDIT.
package {{.PackageName}}

import (
	"github.com/apache/arrow/go/v18/arrow"
	"github.com/apache/arrow/go/v18/arrow/array"
	"github.com/apache/arrow/go/v18/arrow/memory"
{{- range .Imports}}
	{{if .Alias}}{{.Alias}} {{end}}"{{.Path}}"
{{- end}}
)
{{range .Structs}}
// New{{.Name}}Schema returns the Apache Arrow schema for the {{.Name}} struct.
func New{{.Name}}Schema() *arrow.Schema {
	return arrow.NewSchema(
		[]arrow.Field{
{{- range .Fields}}
			{Name: "{{.Name}}", Type: {{.ArrowType}}, Nullable: true},
{{- end}}
		},
		nil,
	)
}

// {{.Name}}ArrowWriter is a strongly-typed Apache Arrow append writer for {{.Name}}.
type {{.Name}}ArrowWriter struct {
	b *array.RecordBuilder
}

// New{{.Name}}ArrowWriter creates a new Arrow append writer for {{.Name}}.
func New{{.Name}}ArrowWriter(pool memory.Allocator) *{{.Name}}ArrowWriter {
	schema := New{{.Name}}Schema()
	return &{{.Name}}ArrowWriter{
		b: array.NewRecordBuilder(pool, schema),
	}
}

// Release releases the underlying memory for the Arrow builder.
func (w *{{.Name}}ArrowWriter) Release() {
	if w.b != nil {
		w.b.Release()
	}
}

// Append appends a row of {{.Name}} directly into the Arrow buffers.
func (w *{{.Name}}ArrowWriter) Append(row *{{.Qualifier}}{{.Name}}) {
{{- template "appendFields" dict "Fields" .Fields "Bldr" "w.b.Field" "Qualifier" .Qualifier}}
}

// Append{{.Name}}Struct appends a row of {{.Name}} directly into an existing StructBuilder.
// This is used for writing nested structs.
func Append{{.Name}}Struct(b *array.StructBuilder, row *{{.Qualifier}}{{.Name}}) {
	b.Append(true)
{{- template "appendFields" dict "Fields" .Fields "Bldr" "b.FieldBuilder" "Qualifier" .Qualifier}}
}

// NewRecord creates a new Arrow Record from the accumulated builder data.
func (w *{{.Name}}ArrowWriter) NewRecord() arrow.Record {
	return w.b.NewRecord()
}
{{end}}
{{- define "appendFields" -}}
{{- range $i, $field := .Fields}}
{{- $bldrExpr := printf "%s(%d)" $.Bldr $i -}}
{{- template "appendValue" dict "Info" $field "Var" (printf "row.%s" $field.Name) "BldrExpr" $bldrExpr "Depth" 0}}
{{- end}}
{{- end}}

{{- define "appendValue" -}}
{{- $info := .Info -}}
{{- $var := .Var -}}
{{- $bldr := .BldrExpr -}}
{{- $d := .Depth -}}
{{- $vn := printf "v%d" $d -}}
{{- if $info.IsStruct}}
	{{- if $info.IsPointer}}
	if {{$var}} == nil {
		{{$bldr}}.(*array.StructBuilder).AppendNull()
	} else {
		Append{{$info.StructName}}Struct({{$bldr}}.(*array.StructBuilder), {{$var}})
	}
	{{- else}}
	Append{{$info.StructName}}Struct({{$bldr}}.(*array.StructBuilder), &{{$var}})
	{{- end}}
{{- else if $info.IsList}}
	if {{$var}} == nil {
		{{$bldr}}.(*array.ListBuilder).AppendNull()
	} else {
		{{$bldr}}.(*array.ListBuilder).Append(true)
		{{$vn}}Bldr := {{$bldr}}.(*array.ListBuilder).ValueBuilder()
		for _, {{$vn}} := range {{$var}} {
			{{- template "appendValue" dict "Info" $info.EltInfo "Var" $vn "BldrExpr" (printf "%sBldr" $vn) "Depth" (add $d 1)}}
		}
	}
{{- else if $info.IsFixedSizeList}}
	{
		{{$bldr}}.(*array.FixedSizeListBuilder).Append(true)
		{{$vn}}Bldr := {{$bldr}}.(*array.FixedSizeListBuilder).ValueBuilder()
		for _, {{$vn}} := range {{$var}} {
			{{- template "appendValue" dict "Info" $info.EltInfo "Var" $vn "BldrExpr" (printf "%sBldr" $vn) "Depth" (add $d 1)}}
		}
	}
{{- else if $info.IsMap}}
	if {{$var}} == nil {
		{{$bldr}}.(*array.MapBuilder).AppendNull()
	} else {
		{{$bldr}}.(*array.MapBuilder).Append(true)
		{{$vn}}KeyBldr := {{$bldr}}.(*array.MapBuilder).KeyBuilder()
		{{$vn}}ValBldr := {{$bldr}}.(*array.MapBuilder).ItemBuilder()
		for {{$vn}}K, {{$vn}}V := range {{$var}} {
			{{$vn}}KeyBldr.({{$info.KeyInfo.ArrowBuilder}}).Append({{$info.KeyInfo.CastType}}({{$vn}}K))
			{{- template "appendValue" dict "Info" $info.EltInfo "Var" (printf "%sV" $vn) "BldrExpr" (printf "%sValBldr" $vn) "Depth" (add $d 1)}}
		}
	}
{{- else if $info.MarshalMethod}}
	{{- if $info.IsPointer}}
	if {{$var}} == nil {
		{{$bldr}}.({{$info.ArrowBuilder}}).AppendNull()
	} else {
	{{- if eq $info.MarshalMethod "MarshalText"}}
		marshalData, _ := {{$var}}.MarshalText()
		{{$bldr}}.({{$info.ArrowBuilder}}).Append(string(marshalData))
	{{- else if eq $info.MarshalMethod "String"}}
		{{$bldr}}.({{$info.ArrowBuilder}}).Append({{$var}}.String())
	{{- else if eq $info.MarshalMethod "MarshalBinary"}}
		marshalData, _ := {{$var}}.MarshalBinary()
		{{$bldr}}.({{$info.ArrowBuilder}}).Append(marshalData)
	{{- end}}
	}
	{{- else}}
	{{- if eq $info.MarshalMethod "MarshalText"}}
	{
		marshalData, _ := {{$var}}.MarshalText()
		{{$bldr}}.({{$info.ArrowBuilder}}).Append(string(marshalData))
	}
	{{- else if eq $info.MarshalMethod "String"}}
	{{$bldr}}.({{$info.ArrowBuilder}}).Append({{$var}}.String())
	{{- else if eq $info.MarshalMethod "MarshalBinary"}}
	{
		marshalData, _ := {{$var}}.MarshalBinary()
		{{$bldr}}.({{$info.ArrowBuilder}}).Append(marshalData)
	}
	{{- end}}
	{{- end}}
{{- else if $info.ConvertMethod}}
	{{- if $info.IsPointer}}
	if {{$var}} == nil {
		{{$bldr}}.({{$info.ArrowBuilder}}).AppendNull()
	} else {
		{{$bldr}}.({{$info.ArrowBuilder}}).Append({{$info.CastType}}({{$var}}.{{$info.ConvertMethod}}()))
	}
	{{- else}}
	{{$bldr}}.({{$info.ArrowBuilder}}).Append({{$info.CastType}}({{$var}}.{{$info.ConvertMethod}}()))
	{{- end}}
{{- else}}
	{{- if $info.IsPointer}}
	if {{$var}} == nil {
		{{$bldr}}.({{$info.ArrowBuilder}}).AppendNull()
	} else {
		{{$bldr}}.({{$info.ArrowBuilder}}).Append({{$info.CastType}}(*{{$var}}))
	}
	{{- else}}
	{{$bldr}}.({{$info.ArrowBuilder}}).Append({{$info.CastType}}({{$var}}))
	{{- end}}
{{- end}}
{{- end}}
`

var writerTemplate = template.Must(template.New("writer").Funcs(template.FuncMap{
	"dict": func(values ...any) map[string]any {
		m := make(map[string]any)
		for i := 0; i < len(values); i += 2 {
			m[values[i].(string)] = values[i+1]
		}
		return m
	},
	"add": func(a, b int) int { return a + b },
}).Parse(writerTemplateStr))

// ImportInfo describes a single package import in the generated file.
type ImportInfo struct {
	Path  string // full import path (e.g. "myapp/entities")
	Name  string // base package name (e.g. "entities")
	Alias string // alias to use in generated code; empty means use Name
}

type templateData struct {
	PackageName string
	Imports     []ImportInfo
	Structs     []StructInfo
}

// Run executes the full generation pipeline: parse -> apply template -> write to file.
//
// If outPkgNameOverride is empty, the output package name is auto-detected from the first input package.
// If outPkgNameOverride is set and differs from a struct's origin package, the generated code will
// import that package and qualify struct type references accordingly.
//
// Package aliases are specified via PkgAliases in "importpath=alias" format, where importpath
// must be the full Go import path of the package (as resolved by packages.Load from the input
// directory). When an alias is provided, the generated import uses that alias and all type
// references are qualified with the alias instead of the base package name.
//
// External package types (e.g., netip.Addr, time.Time) that are NOT in the provided InputPkgs
// are handled through interface-based serialization with the following priority:
//  1. encoding.TextMarshaler — type is serialized to string via MarshalText()
//  2. fmt.Stringer — type is serialized to string via String()
//  3. encoding.BinaryMarshaler — type is serialized to binary via MarshalBinary()
//
// If the external type does not implement any of these interfaces, the field is skipped
// and a warning is emitted during generation.
func (g *Generator) Run(outPkgNameOverride string) error {
	// Parse pkg aliases early so bad input is caught before touching the filesystem.
	pkgAliases := map[string]string{}
	for _, a := range g.PkgAliases {
		parts := strings.SplitN(a, "=", 2)
		if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
			return fmt.Errorf("invalid --pkg-alias %q: expected format 'original=replacement'", a)
		}
		pkgAliases[parts[0]] = parts[1]
	}

	parsedPkgName, _, structs, err := g.Parse()
	if err != nil {
		return err
	}

	if len(structs) == 0 {
		return fmt.Errorf("no target structs found matching specifications")
	}

	// Determine output package name.
	packageName := outPkgNameOverride
	if packageName == "" {
		packageName = parsedPkgName
		if packageName == "" {
			return fmt.Errorf("could not determine package name from input; use --pkg-name to specify one explicitly")
		}
	}

	// resolveAlias returns the alias for a given package import path, or "".
	// The key must be the full Go import path — no short-name or suffix matching.
	resolveAlias := func(pkgPath string) string {
		if alias, ok := pkgAliases[pkgPath]; ok {
			return alias
		}
		return ""
	}

	// Build the import map: collect unique packages that need to be imported.
	// A package needs importing when:
	//   - its name differs from the output package name, OR
	//   - an alias mapping explicitly targets it (forces import even if names match).
	type importKey = string // pkgPath
	importMap := map[importKey]ImportInfo{}
	for _, si := range structs {
		if si.PkgPath == "" {
			continue
		}
		if _, exists := importMap[si.PkgPath]; exists {
			continue
		}
		alias := resolveAlias(si.PkgPath)
		if si.PkgName != packageName || alias != "" {
			importMap[si.PkgPath] = ImportInfo{
				Path:  si.PkgPath,
				Name:  si.PkgName,
				Alias: alias,
			}
		}
	}

	// Convert import map to a sorted slice for deterministic output.
	imports := make([]ImportInfo, 0, len(importMap))
	for _, imp := range importMap {
		imports = append(imports, imp)
	}
	sort.Slice(imports, func(i, j int) bool { return imports[i].Path < imports[j].Path })

	// Validate that reserved Arrow import names don't collide with the output package or any alias.
	hardReserved := map[string]bool{"arrow": true, "array": true, "memory": true}
	for _, imp := range imports {
		effectiveName := imp.Name
		if imp.Alias != "" {
			effectiveName = imp.Alias
		}
		if hardReserved[effectiveName] {
			return fmt.Errorf("imported package alias/name %q collides with a required Arrow import; use --pkg-alias to choose a different alias", effectiveName)
		}
	}
	if hardReserved[packageName] {
		return fmt.Errorf("output package name %q collides with an import used in generated code; choose a different --pkg-name", packageName)
	}

	// Set Qualifier on each StructInfo based on whether it needs an import.
	for i := range structs {
		si := &structs[i]
		if imp, ok := importMap[si.PkgPath]; ok {
			qualifier := imp.Name
			if imp.Alias != "" {
				qualifier = imp.Alias
			}
			si.Qualifier = qualifier + "."
		}
		// else: struct is in the output package — no qualifier needed.
	}

	data := templateData{
		PackageName: packageName,
		Imports:     imports,
		Structs:     structs,
	}

	var buf bytes.Buffer
	if err := writerTemplate.Execute(&buf, data); err != nil {
		return fmt.Errorf("failed to execute template: %w", err)
	}

	// Format Source
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("failed to format generated source: %w\nSource:\n%s", err, buf.String())
	}

	// Write Output
	if err := os.WriteFile(g.OutPath, formatted, 0644); err != nil {
		return fmt.Errorf("failed to write output file: %w", err)
	}

	return nil
}
