package writergen

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"text/template"
)

const writerTemplateStr = `// Code generated by arrow-writer-gen. DO NOT EDIT.
package {{.PackageName}}

import (
	"github.com/apache/arrow/go/v18/arrow"
	"github.com/apache/arrow/go/v18/arrow/array"
	"github.com/apache/arrow/go/v18/arrow/memory"
)
{{range .Structs}}
// New{{.Name}}Schema returns the Apache Arrow schema for the {{.Name}} struct.
func New{{.Name}}Schema() *arrow.Schema {
	return arrow.NewSchema(
		[]arrow.Field{
{{- range .Fields}}
			{Name: "{{.Name}}", Type: {{.ArrowType}}, Nullable: true},
{{- end}}
		},
		nil,
	)
}

// {{.Name}}ArrowWriter is a strongly-typed Apache Arrow append writer for {{.Name}}.
type {{.Name}}ArrowWriter struct {
	b *array.RecordBuilder
}

// New{{.Name}}ArrowWriter creates a new Arrow append writer for {{.Name}}.
func New{{.Name}}ArrowWriter(pool memory.Allocator) *{{.Name}}ArrowWriter {
	schema := New{{.Name}}Schema()
	return &{{.Name}}ArrowWriter{
		b: array.NewRecordBuilder(pool, schema),
	}
}

// Release releases the underlying memory for the Arrow builder.
func (w *{{.Name}}ArrowWriter) Release() {
	if w.b != nil {
		w.b.Release()
	}
}

// Append appends a row of {{.Name}} directly into the Arrow buffers.
func (w *{{.Name}}ArrowWriter) Append(row {{.Name}}) {
{{- range $i, $field := .Fields}}
{{- if .IsStruct}}
	{{- if .IsPointer}}
	if row.{{$field.Name}} == nil {
		w.b.Field({{$i}}).(*array.StructBuilder).AppendNull()
	} else {
		Append{{$field.StructName}}Struct(w.b.Field({{$i}}).(*array.StructBuilder), *row.{{$field.Name}})
	}
	{{- else}}
	Append{{$field.StructName}}Struct(w.b.Field({{$i}}).(*array.StructBuilder), row.{{$field.Name}})
	{{- end}}
{{- else if .IsList}}
	if row.{{$field.Name}} == nil {
		w.b.Field({{$i}}).(*array.ListBuilder).AppendNull()
	} else {
		w.b.Field({{$i}}).(*array.ListBuilder).Append(true)
		{{- if $field.ValIsStruct}}
		valBldr := w.b.Field({{$i}}).(*array.ListBuilder).ValueBuilder().(*array.StructBuilder)
		{{- else}}
		valBldr := w.b.Field({{$i}}).(*array.ListBuilder).ValueBuilder().({{$field.ValArrowBuilder}})
		{{- end}}
		for _, v := range row.{{$field.Name}} {
			{{- if $field.ValIsStruct}}
			{{- if $field.ValIsPointer}}
			if v == nil {
				valBldr.AppendNull()
			} else {
				Append{{$field.ValStructName}}Struct(valBldr, *v)
			}
			{{- else}}
			Append{{$field.ValStructName}}Struct(valBldr, v)
			{{- end}}
			{{- else}}
			valBldr.Append({{$field.ValCastType}}(v))
			{{- end}}
		}
	}
{{- else if .IsMap}}
	if row.{{$field.Name}} == nil {
		w.b.Field({{$i}}).(*array.MapBuilder).AppendNull()
	} else {
		w.b.Field({{$i}}).(*array.MapBuilder).Append(true)
		keyBldr := w.b.Field({{$i}}).(*array.MapBuilder).KeyBuilder().({{$field.KeyArrowBuilder}})
		{{- if $field.ValIsStruct}}
		valBldr := w.b.Field({{$i}}).(*array.MapBuilder).ItemBuilder().(*array.StructBuilder)
		{{- else}}
		valBldr := w.b.Field({{$i}}).(*array.MapBuilder).ItemBuilder().({{$field.ValArrowBuilder}})
		{{- end}}
		for k, v := range row.{{$field.Name}} {
			keyBldr.Append({{$field.KeyCastType}}(k))
			{{- if $field.ValIsStruct}}
			{{- if $field.ValIsPointer}}
			if v == nil {
				valBldr.AppendNull()
			} else {
				Append{{$field.ValStructName}}Struct(valBldr, *v)
			}
			{{- else}}
			Append{{$field.ValStructName}}Struct(valBldr, v)
			{{- end}}
			{{- else}}
			valBldr.Append({{$field.ValCastType}}(v))
			{{- end}}
		}
	}
{{- else}}
	w.b.Field({{$i}}).({{$field.ArrowBuilder}}).Append({{$field.CastType}}(row.{{$field.Name}}))
{{- end}}
{{- end}}
}

// Append{{.Name}}Struct appends a row of {{.Name}} directly into an existing StructBuilder.
// This is used for writing nested structs.
func Append{{.Name}}Struct(b *array.StructBuilder, row {{.Name}}) {
	b.Append(true)
{{- range $i, $field := .Fields}}
{{- if .IsStruct}}
	{{- if .IsPointer}}
	if row.{{$field.Name}} == nil {
		b.FieldBuilder({{$i}}).(*array.StructBuilder).AppendNull()
	} else {
		Append{{$field.StructName}}Struct(b.FieldBuilder({{$i}}).(*array.StructBuilder), *row.{{$field.Name}})
	}
	{{- else}}
	Append{{$field.StructName}}Struct(b.FieldBuilder({{$i}}).(*array.StructBuilder), row.{{$field.Name}})
	{{- end}}
{{- else if .IsList}}
	if row.{{$field.Name}} == nil {
		b.FieldBuilder({{$i}}).(*array.ListBuilder).AppendNull()
	} else {
		b.FieldBuilder({{$i}}).(*array.ListBuilder).Append(true)
		{{- if $field.ValIsStruct}}
		valBldr := b.FieldBuilder({{$i}}).(*array.ListBuilder).ValueBuilder().(*array.StructBuilder)
		{{- else}}
		valBldr := b.FieldBuilder({{$i}}).(*array.ListBuilder).ValueBuilder().({{$field.ValArrowBuilder}})
		{{- end}}
		for _, v := range row.{{$field.Name}} {
			{{- if $field.ValIsStruct}}
			{{- if $field.ValIsPointer}}
			if v == nil {
				valBldr.AppendNull()
			} else {
				Append{{$field.ValStructName}}Struct(valBldr, *v)
			}
			{{- else}}
			Append{{$field.ValStructName}}Struct(valBldr, v)
			{{- end}}
			{{- else}}
			valBldr.Append({{$field.ValCastType}}(v))
			{{- end}}
		}
	}
{{- else if .IsMap}}
	if row.{{$field.Name}} == nil {
		b.FieldBuilder({{$i}}).(*array.MapBuilder).AppendNull()
	} else {
		b.FieldBuilder({{$i}}).(*array.MapBuilder).Append(true)
		keyBldr := b.FieldBuilder({{$i}}).(*array.MapBuilder).KeyBuilder().({{$field.KeyArrowBuilder}})
		{{- if $field.ValIsStruct}}
		valBldr := b.FieldBuilder({{$i}}).(*array.MapBuilder).ItemBuilder().(*array.StructBuilder)
		{{- else}}
		valBldr := b.FieldBuilder({{$i}}).(*array.MapBuilder).ItemBuilder().({{$field.ValArrowBuilder}})
		{{- end}}
		for k, v := range row.{{$field.Name}} {
			keyBldr.Append({{$field.KeyCastType}}(k))
			{{- if $field.ValIsStruct}}
			{{- if $field.ValIsPointer}}
			if v == nil {
				valBldr.AppendNull()
			} else {
				Append{{$field.ValStructName}}Struct(valBldr, *v)
			}
			{{- else}}
			Append{{$field.ValStructName}}Struct(valBldr, v)
			{{- end}}
			{{- else}}
			valBldr.Append({{$field.ValCastType}}(v))
			{{- end}}
		}
	}
{{- else}}
	b.FieldBuilder({{$i}}).({{$field.ArrowBuilder}}).Append({{$field.CastType}}(row.{{$field.Name}}))
{{- end}}
{{- end}}
}

// NewRecord creates a new Arrow Record from the accumulated builder data.
func (w *{{.Name}}ArrowWriter) NewRecord() arrow.Record {
	return w.b.NewRecord()
}
{{end}}
`

var writerTemplate = template.Must(template.New("writer").Parse(writerTemplateStr))

type templateData struct {
	PackageName string
	Structs     []StructInfo
}

// Run executes the full generation pipeline: parse -> apply template -> write to file.
func (g *Generator) Run(packageName string) error {
	structs, err := g.Parse()
	if err != nil {
		return err
	}

	if len(structs) == 0 {
		return fmt.Errorf("no target structs found matching specifications")
	}

	data := templateData{
		PackageName: packageName,
		Structs:     structs,
	}

	var buf bytes.Buffer
	if err := writerTemplate.Execute(&buf, data); err != nil {
		return fmt.Errorf("failed to execute template: %w", err)
	}

	// Format Source
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("failed to format generated source: %w\nSource:\n%s", err, buf.String())
	}

	// Write Output
	if err := os.WriteFile(g.OutPath, formatted, 0644); err != nil {
		return fmt.Errorf("failed to write output file: %w", err)
	}

	return nil
}
