package writergen

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"text/template"
)

// writerTemplateStr is the Go text/template used to generate Arrow append writers.
//
// Template structure:
//
//   - Main template ("writer"): Generates the public API per struct — schema constructor,
//     ArrowWriter struct, New/Release/Append/NewRecord methods, and the AppendStruct helper.
//   - Sub-template ("appendFields"): Shared field-handling logic used by both the Append
//     method (which accesses builders via w.b.Field) and AppendStruct (via b.FieldBuilder).
//     The builder accessor is passed as the "Bldr" key in a dict.
//
// A "dict" FuncMap helper is registered to pass multiple named values to sub-templates,
// since Go's text/template only supports a single pipeline argument to {{template}}.
//
// Template data is provided via the templateData struct. When the output package differs
// from the input package, ImportPkgPath and ImportPkgName are set, causing the template to
// emit an import statement and qualify struct type references with the input package name.
const writerTemplateStr = `// Code generated by arrow-writer-gen. DO NOT EDIT.
package {{.PackageName}}

import (
	"github.com/apache/arrow/go/v18/arrow"
	"github.com/apache/arrow/go/v18/arrow/array"
	"github.com/apache/arrow/go/v18/arrow/memory"
{{- if .ImportPkgPath}}
	{{if .ImportAlias}}{{.ImportAlias}} {{end}}"{{.ImportPkgPath}}"
{{- end}}
)
{{range .Structs}}
// New{{.Name}}Schema returns the Apache Arrow schema for the {{.Name}} struct.
func New{{.Name}}Schema() *arrow.Schema {
	return arrow.NewSchema(
		[]arrow.Field{
{{- range .Fields}}
			{Name: "{{.Name}}", Type: {{.ArrowType}}, Nullable: true},
{{- end}}
		},
		nil,
	)
}

// {{.Name}}ArrowWriter is a strongly-typed Apache Arrow append writer for {{.Name}}.
type {{.Name}}ArrowWriter struct {
	b *array.RecordBuilder
}

// New{{.Name}}ArrowWriter creates a new Arrow append writer for {{.Name}}.
func New{{.Name}}ArrowWriter(pool memory.Allocator) *{{.Name}}ArrowWriter {
	schema := New{{.Name}}Schema()
	return &{{.Name}}ArrowWriter{
		b: array.NewRecordBuilder(pool, schema),
	}
}

// Release releases the underlying memory for the Arrow builder.
func (w *{{.Name}}ArrowWriter) Release() {
	if w.b != nil {
		w.b.Release()
	}
}

// Append appends a row of {{.Name}} directly into the Arrow buffers.
func (w *{{.Name}}ArrowWriter) Append(row {{if $.ImportPkgName}}{{$.ImportPkgName}}.{{end}}{{.Name}}) {
{{- template "appendFields" dict "Fields" .Fields "Bldr" "w.b.Field" "ImportPkgName" $.ImportPkgName}}
}

// Append{{.Name}}Struct appends a row of {{.Name}} directly into an existing StructBuilder.
// This is used for writing nested structs.
func Append{{.Name}}Struct(b *array.StructBuilder, row {{if $.ImportPkgName}}{{$.ImportPkgName}}.{{end}}{{.Name}}) {
	b.Append(true)
{{- template "appendFields" dict "Fields" .Fields "Bldr" "b.FieldBuilder" "ImportPkgName" $.ImportPkgName}}
}

// NewRecord creates a new Arrow Record from the accumulated builder data.
func (w *{{.Name}}ArrowWriter) NewRecord() arrow.Record {
	return w.b.NewRecord()
}
{{end}}
{{- define "appendFields" -}}
{{- range $i, $field := .Fields}}
{{- if .IsStruct}}
	{{- if .IsPointer}}
	if row.{{$field.Name}} == nil {
		{{$.Bldr}}({{$i}}).(*array.StructBuilder).AppendNull()
	} else {
		Append{{$field.StructName}}Struct({{$.Bldr}}({{$i}}).(*array.StructBuilder), {{if $.ImportPkgName}}{{$.ImportPkgName}}.{{end}}{{$field.StructName}}(*row.{{$field.Name}}))
	}
	{{- else}}
	Append{{$field.StructName}}Struct({{$.Bldr}}({{$i}}).(*array.StructBuilder), row.{{$field.Name}})
	{{- end}}
{{- else if .IsList}}
	if row.{{$field.Name}} == nil {
		{{$.Bldr}}({{$i}}).(*array.ListBuilder).AppendNull()
	} else {
		{{$.Bldr}}({{$i}}).(*array.ListBuilder).Append(true)
		{{- if $field.ValIsStruct}}
		valBldr := {{$.Bldr}}({{$i}}).(*array.ListBuilder).ValueBuilder().(*array.StructBuilder)
		{{- else}}
		valBldr := {{$.Bldr}}({{$i}}).(*array.ListBuilder).ValueBuilder().({{$field.ValArrowBuilder}})
		{{- end}}
		for _, v := range row.{{$field.Name}} {
			{{- if $field.ValIsStruct}}
			{{- if $field.ValIsPointer}}
			if v == nil {
				valBldr.AppendNull()
			} else {
				Append{{$field.ValStructName}}Struct(valBldr, {{if $.ImportPkgName}}{{$.ImportPkgName}}.{{end}}{{$field.ValStructName}}(*v))
			}
			{{- else}}
			Append{{$field.ValStructName}}Struct(valBldr, v)
			{{- end}}
			{{- else}}
			{{- if $field.ValIsPointer}}
			if v == nil {
				valBldr.AppendNull()
			} else {
				valBldr.Append({{$field.ValCastType}}(*v))
			}
			{{- else}}
			valBldr.Append({{$field.ValCastType}}(v))
			{{- end}}
			{{- end}}
		}
	}
{{- else if .IsMap}}
	if row.{{$field.Name}} == nil {
		{{$.Bldr}}({{$i}}).(*array.MapBuilder).AppendNull()
	} else {
		{{$.Bldr}}({{$i}}).(*array.MapBuilder).Append(true)
		keyBldr := {{$.Bldr}}({{$i}}).(*array.MapBuilder).KeyBuilder().({{$field.KeyArrowBuilder}})
		{{- if $field.ValIsStruct}}
		valBldr := {{$.Bldr}}({{$i}}).(*array.MapBuilder).ItemBuilder().(*array.StructBuilder)
		{{- else}}
		valBldr := {{$.Bldr}}({{$i}}).(*array.MapBuilder).ItemBuilder().({{$field.ValArrowBuilder}})
		{{- end}}
		for k, v := range row.{{$field.Name}} {
			keyBldr.Append({{$field.KeyCastType}}(k))
			{{- if $field.ValIsStruct}}
			{{- if $field.ValIsPointer}}
			if v == nil {
				valBldr.AppendNull()
			} else {
				Append{{$field.ValStructName}}Struct(valBldr, {{if $.ImportPkgName}}{{$.ImportPkgName}}.{{end}}{{$field.ValStructName}}(*v))
			}
			{{- else}}
			Append{{$field.ValStructName}}Struct(valBldr, v)
			{{- end}}
			{{- else}}
			{{- if $field.ValIsPointer}}
			if v == nil {
				valBldr.AppendNull()
			} else {
				valBldr.Append({{$field.ValCastType}}(*v))
			}
			{{- else}}
			valBldr.Append({{$field.ValCastType}}(v))
			{{- end}}
			{{- end}}
		}
	}
{{- else if .MarshalMethod}}
	{{- if .IsPointer}}
	if row.{{$field.Name}} == nil {
		{{$.Bldr}}({{$i}}).({{$field.ArrowBuilder}}).AppendNull()
	} else {
	{{- if eq .MarshalMethod "MarshalText"}}
		marshalData, _ := row.{{$field.Name}}.MarshalText()
		{{$.Bldr}}({{$i}}).({{$field.ArrowBuilder}}).Append(string(marshalData))
	{{- else if eq .MarshalMethod "String"}}
		{{$.Bldr}}({{$i}}).({{$field.ArrowBuilder}}).Append(row.{{$field.Name}}.String())
	{{- else if eq .MarshalMethod "MarshalBinary"}}
		marshalData, _ := row.{{$field.Name}}.MarshalBinary()
		{{$.Bldr}}({{$i}}).({{$field.ArrowBuilder}}).Append(marshalData)
	{{- end}}
	}
	{{- else}}
	{{- if eq .MarshalMethod "MarshalText"}}
	{
		marshalData, _ := row.{{$field.Name}}.MarshalText()
		{{$.Bldr}}({{$i}}).({{$field.ArrowBuilder}}).Append(string(marshalData))
	}
	{{- else if eq .MarshalMethod "String"}}
	{{$.Bldr}}({{$i}}).({{$field.ArrowBuilder}}).Append(row.{{$field.Name}}.String())
	{{- else if eq .MarshalMethod "MarshalBinary"}}
	{
		marshalData, _ := row.{{$field.Name}}.MarshalBinary()
		{{$.Bldr}}({{$i}}).({{$field.ArrowBuilder}}).Append(marshalData)
	}
	{{- end}}
	{{- end}}
{{- else}}
	{{- if .IsPointer}}
	if row.{{$field.Name}} == nil {
		{{$.Bldr}}({{$i}}).({{$field.ArrowBuilder}}).AppendNull()
	} else {
		{{$.Bldr}}({{$i}}).({{$field.ArrowBuilder}}).Append({{$field.CastType}}(*row.{{$field.Name}}))
	}
	{{- else}}
	{{$.Bldr}}({{$i}}).({{$field.ArrowBuilder}}).Append({{$field.CastType}}(row.{{$field.Name}}))
	{{- end}}
{{- end}}
{{- end}}
{{- end}}
`

var writerTemplate = template.Must(template.New("writer").Funcs(template.FuncMap{
	"dict": func(values ...any) map[string]any {
		m := make(map[string]any)
		for i := 0; i < len(values); i += 2 {
			m[values[i].(string)] = values[i+1]
		}
		return m
	},
}).Parse(writerTemplateStr))

type templateData struct {
	PackageName   string
	ImportPkgPath string
	ImportPkgName string
	ImportAlias   string
	Structs       []StructInfo
}

// Run executes the full generation pipeline: parse -> apply template -> write to file.
//
// If outPkgNameOverride is empty, the output package name is auto-detected from the input package.
// If outPkgNameOverride is set and differs from the input, the generated code will import the
// input package and qualify struct type references accordingly.
//
// External package types (e.g., netip.Addr, time.Time) are handled through interface-based
// serialization with the following priority:
//  1. encoding.TextMarshaler — type is serialized to string via MarshalText()
//  2. fmt.Stringer — type is serialized to string via String()
//  3. encoding.BinaryMarshaler — type is serialized to binary via MarshalBinary()
//
// If the external type does not implement any of these interfaces, the field is skipped
// and a warning is emitted during generation.
func (g *Generator) Run(outPkgNameOverride string) error {
	parsedPkgName, parsedPkgPath, structs, err := g.Parse()
	if err != nil {
		return err
	}

	if len(structs) == 0 {
		return fmt.Errorf("no target structs found matching specifications")
	}

	importPkgPath := ""
	importPkgName := ""
	importAlias := ""

	if g.PkgAlias != "" {
		importPkgPath = parsedPkgPath
		importPkgName = g.PkgAlias
		importAlias = g.PkgAlias
	} else if outPkgNameOverride != "" && outPkgNameOverride != parsedPkgName {
		importPkgPath = parsedPkgPath
		importPkgName = parsedPkgName
	}

	packageName := outPkgNameOverride
	if packageName == "" {
		packageName = parsedPkgName
		if packageName == "" {
			return fmt.Errorf("could not determine package name from input; use --pkg-name to specify one explicitly")
		}
	}

	// Validate that the output package name doesn't collide with imports used in generated code.
	reservedNames := map[string]bool{"arrow": true, "array": true, "memory": true}
	if importPkgName != "" {
		reservedNames[importPkgName] = true
	}
	if reservedNames[packageName] {
		return fmt.Errorf("output package name %q collides with an import used in generated code; choose a different --pkg-name", packageName)
	}

	data := templateData{
		PackageName:   packageName,
		ImportPkgPath: importPkgPath,
		ImportPkgName: importPkgName,
		ImportAlias:   importAlias,
		Structs:       structs,
	}

	var buf bytes.Buffer
	if err := writerTemplate.Execute(&buf, data); err != nil {
		return fmt.Errorf("failed to execute template: %w", err)
	}

	// Format Source
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("failed to format generated source: %w\nSource:\n%s", err, buf.String())
	}

	// Write Output
	if err := os.WriteFile(g.OutPath, formatted, 0644); err != nil {
		return fmt.Errorf("failed to write output file: %w", err)
	}

	return nil
}
