package deltagen

// template_standalone.go implements the standalone-mode code-emission stage.
//
// Standalone mode (--standalone) generates runtime-independent delta code:
// Snapshot structs need not embed runtime.Header, Apply/Diff/Coalesce are pure
// functions with no error return, and no symbols from go.resystems.io/eddt/runtime
// appear in the generated file. A companion delta_types.go (or custom name) is
// emitted alongside the *_delta.go with local equivalents of EntityID, FieldDelta[T],
// FieldDeltaOp, and the hash helpers needed by EntityID().
//
// # Integration with the existing template pipeline
//
// The standalone sub-templates are parsed into the shared deltaTemplate object
// at package init time (via init()). This means all sub-templates defined in
// template.go (nestedTypeDecl, applyField, diffField, fieldDeclsRange, mapWrapper,
// sliceWrapper, etc.) are visible to and reused by the standaloneMain template.
// The only new templates defined here are those that differ in the standalone mode:
// the top-level standaloneMain body and the Apply/Diff/Coalesce/EntityID function
// and method wrapper variants.
//
// # Companion file
//
// emitStandaloneTypes writes the companion local-types file. Its content is
// controlled by standaloneTypesTemplateStr, which is selected based on the
// --standalone-hash flag (blake2b or sha256). The file is only written when
// --standalone is active and the destination file either does not exist or
// already carries a "DO NOT EDIT" marker from a prior run.

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"text/template"
)

// ── Standalone delta-file templates ──────────────────────────────────────────

// standaloneTemplateStr holds the additional named sub-templates for standalone
// mode. These are parsed into deltaTemplate at init time, making them available
// via ExecuteTemplate("standaloneMain", ...).
//
// The standaloneMain template mirrors the structure of the root "delta" template
// in template.go but differs in three ways:
//  1. The TDelta struct omits the runtime.Header embedding.
//  2. Apply, Diff, Coalesce, and EntityID use standalone variants (pure functions,
//     no error return, local EntityID type).
//  3. The import block is conditional to handle the empty-imports case (no
//     runtime import, and some simple snapshots may have no foreign types at all).
const standaloneTemplateStr = `
{{define "standaloneMain"}}// Code generated by delta-gen{{if .Version}} ({{.Version}}){{end}}. DO NOT EDIT.
package {{.PackageName}}
{{if .Imports}}
import (
{{- range .Imports}}
	{{if .Alias}}{{.Alias}} {{end}}"{{.Path}}"
{{- end}}
)
{{end}}{{range .Snapshots}}{{range .NestedTypes}}{{if .IsMapWrapper}}{{template "mapWrapper" .}}{{else if .IsSliceWrapper}}{{template "sliceWrapper" .}}{{else}}{{template "nestedTypeDecl" .}}{{template "nestedApplyFunc" .}}{{if .EmitMethod}}{{template "nestedApplyMethod" .}}{{end}}{{template "nestedDiffFunc" .}}{{if .EmitMethod}}{{template "nestedDiffMethod" .}}{{end}}{{end}}
{{end}}
// {{.DeltaName}} is the Delta companion type for {{.Qualifier}}{{.Name}}.
// Each payload field is expressed as an optional pointer: a nil value means
// "no change" for that field when Apply is called.
// Generated in standalone mode: no runtime.Header embedding, no chain-lifecycle envelope.
type {{.DeltaName}} struct {
{{- template "fieldDeclsRange" dict "Fields" .Fields "ParentName" .Name}}
}
{{template "applyFuncStandalone" .}}
{{if .EmitMethod}}{{template "applyMethodStandalone" .}}
{{end}}{{template "diffFuncStandalone" .}}
{{if .EmitMethod}}{{template "diffMethodStandalone" .}}
{{end}}{{template "coalesceFuncStandalone" .}}
{{if .EmitMethod}}{{template "coalesceMethodStandalone" .}}
{{end}}{{template "entityIDFuncStandalone" .}}
{{if .EmitEntityIDMethod}}{{template "entityIDMethodStandalone" .}}
{{end}}{{end -}}
{{end}}

{{define "applyFuncStandalone"}}
// Apply produces the Snapshot that results from applying d to s. It is a pure
// function with no chain-envelope validation (standalone mode — no runtime.Header).
func Apply(s {{.Qualifier}}{{.Name}}, d {{.DeltaName}}) {{.Qualifier}}{{.Name}} {
	result := s
	result.{{.KeyName}} = s.{{.KeyName}}
{{range .Fields}}	{{template "applyField" .}}
{{end}}	return result
}
{{end -}}

{{define "applyMethodStandalone"}}
// Apply is an ergonomic same-package wrapper (R-DG-012, R-DG-013, R-DG-019).
func (s {{.Name}}) Apply(d {{.DeltaName}}) {{.Name}} {
	return Apply(s, d)
}
{{end -}}

{{define "diffFuncStandalone"}}
// Diff produces the minimal Delta d such that Apply(a, d) payload-equals b. It
// is a pure function with no chain-envelope validation (standalone mode).
func Diff(a, b {{.Qualifier}}{{.Name}}) {{.DeltaName}} {
	d := {{.DeltaName}}{}
{{range .DiffFields}}	{{template "diffField" .}}
{{end}}	return d
}
{{end -}}

{{define "diffMethodStandalone"}}
// Diff is an ergonomic same-package wrapper (R-DG-012, R-DG-013, R-DG-019).
func (a {{.Name}}) Diff(b {{.Name}}) {{.DeltaName}} {
	return Diff(a, b)
}
{{end -}}

{{define "coalesceFuncStandalone"}}
// Coalesce folds a slice of TDeltas into s by iterated Apply. It is a pure
// function with no chain-envelope validation (standalone mode). An empty slice
// returns s unchanged.
func Coalesce(s {{.Qualifier}}{{.Name}}, ds []{{.DeltaName}}) {{.Qualifier}}{{.Name}} {
	result := s
	for _, d := range ds {
		result = Apply(result, d)
	}
	return result
}
{{end -}}

{{define "coalesceMethodStandalone"}}
// Coalesce is an ergonomic same-package wrapper (R-DG-012, R-DG-013, R-DG-019).
func (s {{.Name}}) Coalesce(ds []{{.DeltaName}}) {{.Name}} {
	return Coalesce(s, ds)
}
{{end -}}

{{define "entityIDFuncStandalone"}}
// NewEntityID returns the deterministic content-hash EntityID of k, derived
// from the key field {{.KeyName}} (R-DG-034, R-DG-035). The hash algorithm is
// selected by --standalone-hash at generation time (see delta_types.go).
//
// Note: the function is named NewEntityID (not EntityID) in standalone mode
// because Go does not allow a package-level function and a type to share the
// same identifier. The EntityID type is defined in the companion delta_types.go.
// For named key types, the .EntityID() method wrapper delegates to this function.
func NewEntityID(k {{.KeyQualifier}}{{.KeyTypeName}}) EntityID {
	h := standaloneNewHash()
{{- range .StandaloneKeyHashLines}}
	{{.}}
{{- end}}
	return standaloneFinalise(h)
}
{{end -}}

{{define "entityIDMethodStandalone"}}
// EntityID is an ergonomic same-package wrapper (R-DG-012, R-DG-013, R-DG-019).
// It delegates to NewEntityID, which is the package-level function in standalone mode.
func (k {{.KeyTypeName}}) EntityID() EntityID {
	return NewEntityID(k)
}
{{end}}
`

// init registers the standalone sub-templates with the shared deltaTemplate so
// ExecuteTemplate("standaloneMain", ...) and the standalone function sub-templates
// are available at generation time.
func init() {
	template.Must(deltaTemplate.Parse(standaloneTemplateStr))
}

// ── Companion local-types file ────────────────────────────────────────────────

// standaloneTypesData is the view type for the companion delta_types.go template.
type standaloneTypesData struct {
	Version     string
	PackageName string
	UseSHA256   bool // true when --standalone-hash sha256
}

// standaloneTypesBlake2bStr is the companion file template for blake2b mode.
// The produced EntityID values are byte-identical to runtime.EntityID for the
// same key fields (same algorithm, same encoding).
const standaloneTypesBlake2bStr = `// Code generated by delta-gen{{if .Version}} ({{.Version}}){{end}}. DO NOT EDIT.
package {{.PackageName}}

import (
	"encoding/binary"
	"hash"
	"io"

	"golang.org/x/crypto/blake2b"
)

// EntityID is a content-addressable 32-byte identifier derived from entity key
// fields. When generated with --standalone-hash blake2b (the default), these
// values are byte-identical to runtime.EntityID produced by eddt/runtime for
// the same key fields.
type EntityID [32]byte

// IsZero reports whether the EntityID is the all-zero value.
func (e EntityID) IsZero() bool { return e == EntityID{} }

// FieldDeltaOp identifies the operation a FieldDelta[T] performs.
type FieldDeltaOp uint8

const (
	OpIgnore  FieldDeltaOp = 0 // no change; the zero value
	OpAssert  FieldDeltaOp = 1 // set the field to Value
	OpRetract FieldDeltaOp = 2 // reset the field to its zero value
)

// FieldDelta[T] is a tri-state wrapper for clearable nested delta fields.
// The zero value (Op == OpIgnore) means "leave the field unchanged".
type FieldDelta[T any] struct {
	Op    FieldDeltaOp
	Value T // valid only when Op == OpAssert; ignored otherwise
}

// standaloneNewHash returns a new Blake2b-256 hasher matching the algorithm
// used by go.resystems.io/eddt/runtime.NewHash (R-DG-034, R-DG-035).
func standaloneNewHash() hash.Hash {
	h, _ := blake2b.New256(nil)
	return h
}

// standaloneFinalise extracts the digest and returns it as an EntityID.
func standaloneFinalise(h hash.Hash) EntityID {
	var id EntityID
	h.Sum(id[:0])
	return id
}

// standaloneWriteString appends a length-prefixed UTF-8 string to w.
// Encoding matches runtime.WriteString for EntityID byte-compatibility.
func standaloneWriteString(w io.Writer, v string) {
	standaloneWriteUint64(w, uint64(len(v)))
	_, _ = io.WriteString(w, v)
}

// standaloneWriteBool appends 0x00 for false and 0x01 for true to w.
func standaloneWriteBool(w io.Writer, v bool) {
	if v {
		_, _ = w.Write([]byte{0x01})
	} else {
		_, _ = w.Write([]byte{0x00})
	}
}

// standaloneWriteUint8 appends the single-byte encoding of v to w.
func standaloneWriteUint8(w io.Writer, v uint8) { _, _ = w.Write([]byte{v}) }

// standaloneWriteUint16 appends the 2-byte big-endian encoding of v to w.
func standaloneWriteUint16(w io.Writer, v uint16) {
	var buf [2]byte
	binary.BigEndian.PutUint16(buf[:], v)
	_, _ = w.Write(buf[:])
}

// standaloneWriteUint32 appends the 4-byte big-endian encoding of v to w.
func standaloneWriteUint32(w io.Writer, v uint32) {
	var buf [4]byte
	binary.BigEndian.PutUint32(buf[:], v)
	_, _ = w.Write(buf[:])
}

// standaloneWriteUint64 appends the 8-byte big-endian encoding of v to w.
func standaloneWriteUint64(w io.Writer, v uint64) {
	var buf [8]byte
	binary.BigEndian.PutUint64(buf[:], v)
	_, _ = w.Write(buf[:])
}
`

// standaloneTypesSHA256Str is the companion file template for sha256 mode.
// NOTE: EntityID values produced here differ from eddt/runtime EntityID values.
const standaloneTypesSHA256Str = `// Code generated by delta-gen{{if .Version}} ({{.Version}}){{end}}. DO NOT EDIT.
package {{.PackageName}}

// WARNING: EntityID values produced by this file use SHA-256 and are NOT
// compatible with EntityID values produced by eddt/runtime (Blake2b-256).
// Use --standalone-hash blake2b (the default) if compatibility is required.

import (
	"crypto/sha256"
	"encoding/binary"
	"hash"
	"io"
)

// EntityID is a content-addressable 32-byte identifier derived from entity key
// fields. NOTE: these values differ from runtime.EntityID (SHA-256 vs Blake2b-256).
type EntityID [32]byte

// IsZero reports whether the EntityID is the all-zero value.
func (e EntityID) IsZero() bool { return e == EntityID{} }

// FieldDeltaOp identifies the operation a FieldDelta[T] performs.
type FieldDeltaOp uint8

const (
	OpIgnore  FieldDeltaOp = 0 // no change; the zero value
	OpAssert  FieldDeltaOp = 1 // set the field to Value
	OpRetract FieldDeltaOp = 2 // reset the field to its zero value
)

// FieldDelta[T] is a tri-state wrapper for clearable nested delta fields.
// The zero value (Op == OpIgnore) means "leave the field unchanged".
type FieldDelta[T any] struct {
	Op    FieldDeltaOp
	Value T // valid only when Op == OpAssert; ignored otherwise
}

// standaloneNewHash returns a new SHA-256 hasher.
func standaloneNewHash() hash.Hash { return sha256.New() }

// standaloneFinalise extracts the digest and returns it as an EntityID.
func standaloneFinalise(h hash.Hash) EntityID {
	var id EntityID
	h.Sum(id[:0])
	return id
}

// standaloneWriteString appends a length-prefixed UTF-8 string to w.
func standaloneWriteString(w io.Writer, v string) {
	standaloneWriteUint64(w, uint64(len(v)))
	_, _ = io.WriteString(w, v)
}

// standaloneWriteBool appends 0x00 for false and 0x01 for true to w.
func standaloneWriteBool(w io.Writer, v bool) {
	if v {
		_, _ = w.Write([]byte{0x01})
	} else {
		_, _ = w.Write([]byte{0x00})
	}
}

// standaloneWriteUint8 appends the single-byte encoding of v to w.
func standaloneWriteUint8(w io.Writer, v uint8) { _, _ = w.Write([]byte{v}) }

// standaloneWriteUint16 appends the 2-byte big-endian encoding of v to w.
func standaloneWriteUint16(w io.Writer, v uint16) {
	var buf [2]byte
	binary.BigEndian.PutUint16(buf[:], v)
	_, _ = w.Write(buf[:])
}

// standaloneWriteUint32 appends the 4-byte big-endian encoding of v to w.
func standaloneWriteUint32(w io.Writer, v uint32) {
	var buf [4]byte
	binary.BigEndian.PutUint32(buf[:], v)
	_, _ = w.Write(buf[:])
}

// standaloneWriteUint64 appends the 8-byte big-endian encoding of v to w.
func standaloneWriteUint64(w io.Writer, v uint64) {
	var buf [8]byte
	binary.BigEndian.PutUint64(buf[:], v)
	_, _ = w.Write(buf[:])
}
`

var (
	standaloneTypesBlake2bTemplate = template.Must(
		template.New("standalone-types-blake2b").Parse(standaloneTypesBlake2bStr))
	standaloneTypesSHA256Template = template.Must(
		template.New("standalone-types-sha256").Parse(standaloneTypesSHA256Str))
)

// emitStandaloneTypes writes the companion local-types file (default delta_types.go)
// for standalone mode. It is called by Generator.emitStage after the *_delta.go
// file has been written. The output directory is derived from g.OutPath.
//
// If the target file already exists and does NOT carry a "DO NOT EDIT" header
// (indicating a hand-written file), the function warns and skips rather than
// overwriting. On subsequent generator runs the file is overwritten in place.
func emitStandaloneTypes(g *Generator) error {
	outDir := filepath.Dir(g.OutPath)
	typesName := g.StandaloneTypesFile
	if typesName == "" {
		typesName = "delta_types.go"
	}
	typesPath := filepath.Join(outDir, typesName)

	// Guard against overwriting hand-written files.
	if existing, err := os.ReadFile(typesPath); err == nil {
		if !bytes.Contains(existing, []byte("DO NOT EDIT")) {
			g.log().Warn("standalone-types: skipping — file exists without DO NOT EDIT marker",
				"path", typesPath)
			return nil
		}
	}

	data := standaloneTypesData{
		Version:     g.Version,
		PackageName: g.OutPkgName,
		UseSHA256:   g.StandaloneHash == "sha256",
	}

	tmpl := standaloneTypesBlake2bTemplate
	if data.UseSHA256 {
		tmpl = standaloneTypesSHA256Template
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("delta-gen: standalone types template execution failed: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf(
			"delta-gen: standalone types source is not valid Go: %w\n--- raw source ---\n%s",
			err, buf.String())
	}

	if err := os.WriteFile(typesPath, formatted, 0644); err != nil {
		return fmt.Errorf("delta-gen: writing standalone types file %q: %w", typesPath, err)
	}

	return nil
}
