// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package assertion

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AssertionT struct {
	Ttl int64  `json:"ttl"`
	Exp int64  `json:"exp"`
	Sid string `json:"sid"`
	Si  string `json:"si"`
	Di  string `json:"di"`
	St  string `json:"st"`
	Dt  string `json:"dt"`
}

func (t *AssertionT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	sidOffset := flatbuffers.UOffsetT(0)
	if t.Sid != "" {
		sidOffset = builder.CreateString(t.Sid)
	}
	siOffset := flatbuffers.UOffsetT(0)
	if t.Si != "" {
		siOffset = builder.CreateString(t.Si)
	}
	diOffset := flatbuffers.UOffsetT(0)
	if t.Di != "" {
		diOffset = builder.CreateString(t.Di)
	}
	stOffset := flatbuffers.UOffsetT(0)
	if t.St != "" {
		stOffset = builder.CreateString(t.St)
	}
	dtOffset := flatbuffers.UOffsetT(0)
	if t.Dt != "" {
		dtOffset = builder.CreateString(t.Dt)
	}
	AssertionStart(builder)
	AssertionAddTtl(builder, t.Ttl)
	AssertionAddExp(builder, t.Exp)
	AssertionAddSid(builder, sidOffset)
	AssertionAddSi(builder, siOffset)
	AssertionAddDi(builder, diOffset)
	AssertionAddSt(builder, stOffset)
	AssertionAddDt(builder, dtOffset)
	return AssertionEnd(builder)
}

func (rcv *Assertion) UnPackTo(t *AssertionT) {
	t.Ttl = rcv.Ttl()
	t.Exp = rcv.Exp()
	t.Sid = string(rcv.Sid())
	t.Si = string(rcv.Si())
	t.Di = string(rcv.Di())
	t.St = string(rcv.St())
	t.Dt = string(rcv.Dt())
}

func (rcv *Assertion) UnPack() *AssertionT {
	if rcv == nil {
		return nil
	}
	t := &AssertionT{}
	rcv.UnPackTo(t)
	return t
}

type Assertion struct {
	_tab flatbuffers.Table
}

func GetRootAsAssertion(buf []byte, offset flatbuffers.UOffsetT) *Assertion {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Assertion{}
	x.Init(buf, n+offset)
	return x
}

func FinishAssertionBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAssertion(buf []byte, offset flatbuffers.UOffsetT) *Assertion {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Assertion{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAssertionBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Assertion) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Assertion) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Assertion) Ttl() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Assertion) MutateTtl(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func (rcv *Assertion) Exp() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Assertion) MutateExp(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func (rcv *Assertion) Sid() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Assertion) Si() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Assertion) Di() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Assertion) St() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Assertion) Dt() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func AssertionStart(builder *flatbuffers.Builder) {
	builder.StartObject(7)
}
func AssertionAddTtl(builder *flatbuffers.Builder, ttl int64) {
	builder.PrependInt64Slot(0, ttl, 0)
}
func AssertionAddExp(builder *flatbuffers.Builder, exp int64) {
	builder.PrependInt64Slot(1, exp, 0)
}
func AssertionAddSid(builder *flatbuffers.Builder, sid flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(sid), 0)
}
func AssertionAddSi(builder *flatbuffers.Builder, si flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(si), 0)
}
func AssertionAddDi(builder *flatbuffers.Builder, di flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(di), 0)
}
func AssertionAddSt(builder *flatbuffers.Builder, st flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(st), 0)
}
func AssertionAddDt(builder *flatbuffers.Builder, dt flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(dt), 0)
}
func AssertionEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
