#!/usr/bin/env python3
"""Shared internal toolkit for the markdown-*.py script family.

Not a standalone tool — this module has no ``main()`` and is not meant to
be invoked directly. It is imported by the markdown-*.py scripts in this
directory (``markdown-toc.py``, ``markdown-pdf.py``, ``markdown-num.py``,
``markdown-index.py``, ``refs-linkify.py``, ...) so they share one
implementation of logic they'd otherwise each reinvent slightly
differently — starting with comment/fence-aware line scanning, and
intended to grow to cover other recurring patterns across the family
(anchor-slug generation, generated-block marker handling, and so on) as
they're identified.

The first capability this module provides answers a question each script
independently needed to ask: "is this line real markdown content, or is
it inside a fenced code block / an HTML comment and should be ignored
when scanning for headings?" That question was previously answered by
separate, independently-written regexes in each script — none of which
accounted for HTML comments. A ``##``/``###`` line inside a commented-out
block (e.g. rough notes left in a document preamble) was mistaken for a
real heading: TOC insertion landed inside the comment (corrupting it), a
document's title was picked up from inside a comment, the preamble/body
split severed a comment mid-way so its closing ``-->`` ended up on the
wrong side, and section renumbering rewrote or warned about a heading
that was never meant to be visible. Fixing this independently in each
script the first three times is what motivated pulling it out here
instead of writing a fourth divergent copy.

Each script that imports this module remains independently runnable and
does not depend on any of the *other* markdown-*.py scripts — only on this
shared module, which is expected to be packaged and evolve alongside them
in the same directory. Because Python adds a directly-executed script's
own directory to ``sys.path[0]`` regardless of the caller's working
directory, a plain ``import _markdown_shared`` resolves correctly
wherever a script is invoked from, as long as this file ships alongside it.
"""

import re
from pathlib import Path


FENCE_RE = re.compile(r"^```")
COMMENT_START = "<!--"
COMMENT_END = "-->"

# The TOC block's delimiter comments. markdown-toc.py generates and
# strips this block; markdown-pdf.py independently strips it before
# rendering (the TOC is regenerated as a live HTML <div>, not carried
# through to the PDF as markdown). Both previously retyped these two
# literal strings independently — a drift risk if the marker text ever
# changed in only one place. Single source of truth here.
TOC_START = "<!-- TOC generated by scripts/markdown-toc.py -->"
TOC_END = "<!-- /TOC -->"


def real_line_flags(lines: list[str]) -> list[bool]:
    """Return, per line, whether it is real markdown content — i.e. not
    inside a fenced code block and not inside an HTML comment.

    Fences and comments are each tracked with their own toggle, checked in
    that order per line:

    * A fence delimiter line always toggles fence state and is itself
      excluded.
    * A line containing ``<!--`` is always excluded, regardless of what
      follows. If ``-->`` does not also appear after that ``<!--`` on the
      same line, every subsequent line is excluded until one containing
      ``-->`` is seen (inclusive). A same-line self-closing comment (e.g.
      ``<!-- TOC generated ... -->``) therefore marks only that one line —
      required so a tool's own delimiter comments are never mistaken for
      an unclosed comment that would swallow real content after them.

    `lines` must not carry trailing newline characters (i.e. produced via
    ``text.splitlines()`` or ``line.rstrip("\\n")``, not
    ``splitlines(keepends=True)``).
    """
    flags = []
    in_fence = False
    in_comment = False
    for line in lines:
        if FENCE_RE.match(line):
            in_fence = not in_fence
            flags.append(False)
            continue
        if in_fence:
            flags.append(False)
            continue
        if in_comment:
            flags.append(False)
            if COMMENT_END in line:
                in_comment = False
            continue
        start = line.find(COMMENT_START)
        if start != -1:
            flags.append(False)
            if COMMENT_END not in line[start + len(COMMENT_START):]:
                in_comment = True
            continue
        flags.append(True)
    return flags


def find_first_real_match(text: str, line_pattern: "re.Pattern[str]"):
    """Return the match of `line_pattern` against the first real (not
    fenced, not commented) line in `text`, or ``None`` if no real line
    matches.

    `line_pattern` is matched against each candidate line's own content
    via ``.match()`` — it should not include ``^``/``$``/``re.MULTILINE``,
    since it is applied one line at a time internally.

    The returned match's span indexes into the ORIGINAL `text` (not just
    the matched line), so callers can slice `text` directly from the
    result or read capture groups without any offset bookkeeping of their
    own. This is done by locating the candidate line via
    ``real_line_flags``, then re-running ``line_pattern.match(text, pos=
    offset)`` at that line's known offset in `text`.
    """
    raw_lines = text.splitlines(keepends=True)
    stripped = [line.rstrip("\n") for line in raw_lines]
    offset = 0
    for line, is_real, raw in zip(stripped, real_line_flags(stripped), raw_lines):
        if is_real:
            m = line_pattern.match(line)
            if m:
                return line_pattern.match(text, offset)
        offset += len(raw)
    return None


def strip_marked_block(text: str, start: str, end: str) -> tuple[str, str, bool]:
    """Split `text` around a block bounded by two lines that, stripped
    of trailing whitespace, exactly equal `start` and `end` (whole-line
    match — safer than a substring search, which could false-positive on
    the marker text appearing embedded in unrelated content, e.g. inside
    a fenced code example). Trailing whitespace (not just a newline) is
    ignored so a marker line with accidental trailing spaces still
    matches.

    found=True: `(before, after)` are the text strictly outside the
    marker lines — both marker lines themselves are consumed. No
    surrounding blank-line normalisation is applied; callers apply their
    own, since that policy differs per script (some collapse all
    trailing blank lines, some only one, some none).

    found=False: the start marker was not found anywhere, OR it was
    found with no matching end marker after it. `before` is the
    original `text` unchanged, `after` is `""`. Callers needing a
    fallback for "start found, no end" (a legacy format, content-shape-
    based recovery, or discarding to EOF) implement it themselves on top
    of this — those policies genuinely differ per script and aren't
    unified here.
    """
    lines = text.splitlines(keepends=True)
    start_idx = next(
        (i for i, ln in enumerate(lines) if ln.rstrip() == start),
        None,
    )
    if start_idx is None:
        return text, "", False
    end_idx = None
    for j in range(start_idx + 1, len(lines)):
        if lines[j].rstrip() == end:
            end_idx = j + 1
            break
    if end_idx is None:
        return text, "", False
    return "".join(lines[:start_idx]), "".join(lines[end_idx:]), True


def heading_to_anchor(heading: str) -> str:
    """Convert a markdown heading to a GitHub-compatible anchor.

    Moved here from markdown-toc.py and markdown-index.py, which
    previously each carried a byte-identical copy of this function.
    """
    anchor = heading.lower()
    anchor = re.sub(r"[^\w\s-]", "", anchor)  # strip punctuation
    anchor = re.sub(r"\s+", "-", anchor.strip())
    return anchor


def write_if_changed(path: Path, new_text: str, original_text: str) -> bool:
    """Write `new_text` to `path` unless it equals `original_text`.

    Returns ``True`` if a write occurred, ``False`` if the file (and its
    mtime) were left untouched — the no-op-if-unchanged guarantee that
    makes these scripts safe to wire into Makefile dependency chains
    without triggering spurious downstream rebuilds.

    Callers own their own status message: the exact wording and extra
    metadata reported (heading counts, resolved/unknown reference
    tallies, etc.) legitimately differs per script, and some scripts
    print on both the changed and unchanged paths while others are
    silent on one of them — this function only makes the write/no-op
    decision.
    """
    if new_text == original_text:
        return False
    path.write_text(new_text)
    return True
