#!/usr/bin/env python3
"""Generate or regenerate a table of contents in a markdown document.

Usage:
    ./scripts/markdown-toc.py docs/analysis-eddt-context.md

The TOC is inserted (or replaced) just before the first ## heading in the
document — after any opening material (title, preamble, cross-reference
links). The TOC lists all ## and ### headings as a nested bullet list with
anchor links.

The TOC block is delimited by HTML comments so it can be identified and
replaced on subsequent runs:

    <!-- TOC generated by scripts/markdown-toc.py -->
    ...
    <!-- /TOC -->

Fenced code blocks are skipped when scanning for headings.
"""

import re
import sys
from pathlib import Path


TOC_START = "<!-- TOC generated by scripts/markdown-toc.py -->"
TOC_END = "<!-- /TOC -->"

HEADING_RE = re.compile(r"^(#{2,3})\s+(.+)$")
FENCE_RE = re.compile(r"^```")


def heading_to_anchor(heading: str) -> str:
    """Convert a markdown heading to a GitHub-compatible anchor."""
    anchor = heading.lower()
    anchor = re.sub(r"[^\w\s-]", "", anchor)  # strip punctuation
    anchor = re.sub(r"\s+", "-", anchor.strip())
    return anchor


def extract_headings(lines: list[str]) -> list[tuple[int, str]]:
    """Return [(level, heading_text), ...] for ## and ### headings.

    Skips headings inside fenced code blocks.
    """
    headings = []
    in_fence = False
    for line in lines:
        if FENCE_RE.match(line):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        m = HEADING_RE.match(line)
        if m:
            level = len(m.group(1))  # 2 for ##, 3 for ###
            headings.append((level, m.group(2)))
    return headings


def build_toc(headings: list[tuple[int, str]]) -> str:
    """Build the TOC block as a string."""
    lines = [TOC_START, ""]
    for level, text in headings:
        anchor = heading_to_anchor(text)
        indent = "  " if level == 3 else ""
        lines.append(f"{indent}- [{text}](#{anchor})")
    lines.append("")
    lines.append(TOC_END)
    return "\n".join(lines)


def find_first_h2(text: str) -> int:
    """Return the character offset of the first ## heading in the document."""
    m = re.search(r"^## ", text, re.MULTILINE)
    if m:
        return m.start()
    return -1


def strip_existing_toc(text: str) -> str:
    """Remove any existing TOC block (between TOC_START and TOC_END)."""
    start = text.find(TOC_START)
    if start < 0:
        return text
    end = text.find(TOC_END, start)
    if end < 0:
        return text
    end += len(TOC_END)
    # Also strip surrounding blank lines
    while end < len(text) and text[end] == "\n":
        end += 1
    before = text[:start].rstrip("\n") + "\n"
    after = text[end:]
    return before + "\n" + after


def main() -> None:
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <document.md>", file=sys.stderr)
        sys.exit(1)

    path = Path(sys.argv[1])
    original = path.read_text()

    # Strip any existing TOC first
    text = strip_existing_toc(original)

    # Find insertion point (just before first ## heading)
    insert_at = find_first_h2(text)
    if insert_at < 0:
        print("No ## headings found.", file=sys.stderr)
        sys.exit(1)

    # Extract headings from the full document (after stripping old TOC)
    headings = extract_headings(text.splitlines())
    if not headings:
        print("No headings found.", file=sys.stderr)
        sys.exit(1)

    toc = build_toc(headings)

    # Insert TOC before the first ## heading
    before = text[:insert_at].rstrip("\n") + "\n\n"
    after = text[insert_at:]
    result = before + toc + "\n\n" + after

    # No-op-if-unchanged: skip the write when the committed TOC is
    # already up-to-date. Preserves mtime so the script is safe to
    # invoke from build dependency chains without triggering spurious
    # downstream rebuilds.
    if result == original:
        print(f"  TOC {path} (no changes, {len(headings)} headings)")
        return

    path.write_text(result)
    print(f"  TOC {path} ({len(headings)} headings)")


if __name__ == "__main__":
    main()
