#!/usr/bin/env python3
"""Regenerate the alphabetical index at the end of a markdown document.

Usage:
    ./scripts/markdown-index.py docs/analysis-eddt-glossary.md
    ./scripts/markdown-index.py docs/analysis-eddt-stakeholders.md

Reads a markdown document with numbered ## sections containing ###
entries, and replaces (or appends) an "## Alphabetical Index" section
at the end of the file with a freshly generated alphabetical index.

Each index entry is a reference-style markdown link:
    - [Entry][ref] -- Section Name

Reference definitions are collected at the bottom:
    [ref]: #anchor "Entry"

Works on any markdown document that follows the ## N. Section / ### Entry
heading convention (e.g. glossaries, stakeholder registers).
"""

import re
import sys
from pathlib import Path


INDEX_HEADING = "## Alphabetical Index"
SECTION_RE = re.compile(r"^## \d+\.\s+(.+)$")
TERM_RE = re.compile(r"^### (.+)$")

# End marker bracketing the generated Alphabetical Index block. The
# start marker is the ``INDEX_HEADING`` itself. Legacy files without
# an end marker fall back to "strip from heading to EOF" — matching
# the previous behaviour — and gain the end marker on next write.
GENERATED_END = "<!-- /Alphabetical Index -->"


def heading_to_anchor(heading: str) -> str:
    """Convert a markdown heading to a GitHub-compatible anchor."""
    anchor = heading.lower()
    anchor = re.sub(r"[^\w\s-]", "", anchor)  # strip punctuation
    anchor = re.sub(r"\s+", "-", anchor.strip())
    return anchor


def short_ref(heading: str) -> str:
    """Produce a short kebab-case reference key from a heading."""
    # Strip parenthetical abbreviations e.g. "Point-of-View (POV)" -> "pov"
    # Matches uppercase (EDDT, POV) and mixed-case (ConOps, OpsCon, SoI)
    m = re.search(r"\(([A-Za-z]{2,})\)", heading)
    if m:
        return m.group(1).lower()

    # Otherwise kebab-case the full heading, abbreviated
    key = heading.lower()
    key = re.sub(r"[^\w\s-]", "", key)
    key = re.sub(r"\s+", "-", key.strip())
    return key


def extract_terms(lines: list[str]) -> list[tuple[str, str]]:
    """Return [(term_heading, section_name), ...] from the glossary body."""
    terms = []
    current_section = ""
    for line in lines:
        sm = SECTION_RE.match(line)
        if sm:
            current_section = sm.group(1)
            continue
        tm = TERM_RE.match(line)
        if tm:
            terms.append((tm.group(1), current_section))
    return terms


def build_index(terms: list[tuple[str, str]]) -> str:
    """Build the alphabetical index section as a string.

    The block is bracketed by ``INDEX_HEADING`` (start) and
    ``GENERATED_END`` (end); downstream locators use these markers to
    replace the block in place without over-consuming surrounding
    content.
    """
    sorted_terms = sorted(terms, key=lambda t: t[0].lower().lstrip('"'))

    entries = []
    refs = []
    for heading, section in sorted_terms:
        ref = short_ref(heading)
        anchor = heading_to_anchor(heading)
        entries.append(f"- [{heading}][{ref}] -- {section}")
        refs.append(f'[{ref}]: #{anchor} "{heading}"')

    script_name = Path(sys.argv[0]).name
    generated = f"<!-- Generated by scripts/{script_name} — re-run after adding or renaming entries. -->"
    lines = [INDEX_HEADING, "", generated, ""]
    lines.extend(entries)
    lines.append("")
    lines.extend(refs)
    lines.append("")
    lines.append(GENERATED_END)
    lines.append("")
    return "\n".join(lines)


def locate_existing_index(text: str) -> tuple[str, str, bool]:
    """Return (before, after, found) surrounding an existing index block.

    * ``before`` — everything up to (but not including) ``INDEX_HEADING``.
    * ``after``  — everything after the block's end.
    * ``found``  — ``True`` if an existing block was located.

    Block end is identified by ``GENERATED_END`` when present
    (authoritative). For legacy files without an end marker the block
    is treated as extending to EOF — matching the previous behaviour.
    """
    idx = text.find(INDEX_HEADING)
    if idx < 0:
        return text, "", False

    before = text[:idx]
    tail = text[idx:]

    end_pos = tail.find(GENERATED_END)
    if end_pos >= 0:
        # Consume the end marker line itself, and any single trailing
        # newline that normally follows it.
        end_pos += len(GENERATED_END)
        if end_pos < len(tail) and tail[end_pos] == "\n":
            end_pos += 1
        after = tail[end_pos:]
    else:
        # Legacy: no end marker; treat from heading to EOF as the block.
        after = ""

    return before, after, True


def main() -> None:
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <document.md>", file=sys.stderr)
        sys.exit(1)

    path = Path(sys.argv[1])
    text = path.read_text()

    # Locate any existing index block, so content after it (e.g. a
    # reference-definitions block appended by other tooling) is
    # preserved. On a new file we introduce the block at EOF with a
    # preceding `---` separator.
    before, after, found = locate_existing_index(text)

    if found:
        body_for_terms = before.rstrip() + "\n\n"
    else:
        body_for_terms = text.rstrip() + "\n\n---\n\n"

    # Only parse the body (before the index) for terms.
    terms = extract_terms(body_for_terms.splitlines())
    if not terms:
        print("No ### headings found.", file=sys.stderr)
        sys.exit(1)

    index = build_index(terms)

    if found:
        output = before.rstrip() + "\n\n" + index
        trailing = after.lstrip()
        if trailing:
            output = output.rstrip() + "\n\n" + trailing
    else:
        output = body_for_terms + index

    # Ensure file ends with exactly one trailing newline.
    output = output.rstrip() + "\n"
    path.write_text(output)
    print(f"  INDEX {path} ({len(terms)} terms)")


if __name__ == "__main__":
    main()
