#!/usr/bin/env python3
"""Generate or regenerate a table of contents in a markdown document.

Usage:
    ./scripts/markdown-toc.py docs/eddt-context.md

The TOC is inserted (or replaced) just before the first ## heading in the
document — after any opening material (title, preamble, cross-reference
links). The TOC lists all ## and ### headings as a nested bullet list with
anchor links.

The TOC block is delimited by HTML comments so it can be identified and
replaced on subsequent runs:

    <!-- TOC generated by scripts/markdown-toc.py -->
    ...
    <!-- /TOC -->

Fenced code blocks and HTML comments are skipped when scanning for
headings, and when locating the TOC insertion point (see the shared
``_markdown_shared`` module, which must live alongside this script).
"""

import re
import sys
from pathlib import Path

import _markdown_shared


# Single source of truth for these two literals lives in _markdown_shared
# (markdown-pdf.py independently strips this same block and previously
# retyped the identical strings — see _markdown_shared.TOC_START/TOC_END).
TOC_START = _markdown_shared.TOC_START
TOC_END = _markdown_shared.TOC_END

HEADING_RE = re.compile(r"^(#{2,3})\s+(.+)$")
H2_RE = re.compile(r"## ")


def extract_headings(lines: list[str]) -> list[tuple[int, str]]:
    """Return [(level, heading_text), ...] for ## and ### headings.

    Skips headings inside fenced code blocks and HTML comments (see
    ``_markdown_shared.real_line_flags``) — otherwise a ``##``/``###``
    line buried in a leading comment (e.g. commented-out rough notes) is
    mistaken for a real heading and pollutes the generated TOC list.
    """
    headings = []
    for line, is_real in zip(lines, _markdown_shared.real_line_flags(lines)):
        if not is_real:
            continue
        m = HEADING_RE.match(line)
        if m:
            level = len(m.group(1))  # 2 for ##, 3 for ###
            headings.append((level, m.group(2)))
    return headings


def build_toc(headings: list[tuple[int, str]]) -> str:
    """Build the TOC block as a string."""
    lines = [TOC_START, ""]
    for level, text in headings:
        anchor = _markdown_shared.heading_to_anchor(text)
        indent = "  " if level == 3 else ""
        lines.append(f"{indent}- [{text}](#{anchor})")
    lines.append("")
    lines.append(TOC_END)
    return "\n".join(lines)


def find_first_h2(text: str) -> int:
    """Return the character offset of the first real ## heading in the
    document, skipping fenced code blocks and HTML comments (see
    ``_markdown_shared.find_first_real_match``). Returns -1 if none is
    found.
    """
    m = _markdown_shared.find_first_real_match(text, H2_RE)
    return m.start() if m else -1


def strip_existing_toc(text: str) -> str:
    """Remove any existing TOC block (between TOC_START and TOC_END)."""
    before, after, found = _markdown_shared.strip_marked_block(text, TOC_START, TOC_END)
    if not found:
        return text
    # Normalise the separator: exactly one blank line before the cut,
    # and consume any (further) blank lines immediately after it —
    # strip_marked_block only consumes the marker lines themselves.
    before = before.rstrip("\n") + "\n"
    after = after.lstrip("\n")
    return before + "\n" + after


def main() -> None:
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <document.md>", file=sys.stderr)
        sys.exit(1)

    path = Path(sys.argv[1])
    original = path.read_text()

    # Strip any existing TOC first
    text = strip_existing_toc(original)

    # Find insertion point (just before first ## heading)
    insert_at = find_first_h2(text)
    if insert_at < 0:
        print("No ## headings found.", file=sys.stderr)
        sys.exit(1)

    # Extract headings from the full document (after stripping old TOC)
    headings = extract_headings(text.splitlines())
    if not headings:
        print("No headings found.", file=sys.stderr)
        sys.exit(1)

    toc = build_toc(headings)

    # Insert TOC before the first ## heading
    before = text[:insert_at].rstrip("\n") + "\n\n"
    after = text[insert_at:]
    result = before + toc + "\n\n" + after

    # No-op-if-unchanged: skip the write when the committed TOC is
    # already up-to-date. Preserves mtime so the script is safe to
    # invoke from build dependency chains without triggering spurious
    # downstream rebuilds.
    if _markdown_shared.write_if_changed(path, result, original):
        print(f"  TOC {path} ({len(headings)} headings)")
    else:
        print(f"  TOC {path} (no changes, {len(headings)} headings)")


if __name__ == "__main__":
    main()
