// Code generated by delta-gen. DO NOT EDIT.
package pump

import (
	"go.resystems.io/eddt/runtime"
	"time"
)

// SiteAddressDelta is the Delta companion type for delta.nested fields of
// type SiteAddress. It is generated by delta-gen and must not be edited.
type SiteAddressDelta struct {
	// Street: source SiteAddress.Street (string) — atomic replace; nil = no change.
	SetStreet *string
	// City: source SiteAddress.City (string) — atomic replace; nil = no change.
	SetCity *string
}

// ApplySiteAddress produces the SiteAddress that results from applying d to u.
// It is a pure function with no chain-envelope validation (delta-gen spec §4.3).
func ApplySiteAddress(u SiteAddress, d SiteAddressDelta) SiteAddress {
	result := u
	if d.SetStreet != nil {
		result.Street = *d.SetStreet
	} else {
		result.Street = u.Street
	}
	if d.SetCity != nil {
		result.City = *d.SetCity
	} else {
		result.City = u.City
	}
	return result
}

// Apply is an ergonomic same-package wrapper (R-DG-012, R-DG-013, R-DG-019).
func (u SiteAddress) Apply(d SiteAddressDelta) SiteAddress { return ApplySiteAddress(u, d) }

// DiffSiteAddress produces the minimal SiteAddressDelta such that ApplySiteAddress(a, d)
// payload-equals b. Pure function, no chain-envelope validation (delta-gen spec §4.3).
func DiffSiteAddress(a, b SiteAddress) SiteAddressDelta {
	d := SiteAddressDelta{}
	if a.Street != b.Street {
		d.SetStreet = &b.Street
	}
	if a.City != b.City {
		d.SetCity = &b.City
	}
	return d
}

// Diff is an ergonomic same-package wrapper (R-DG-012, R-DG-013, R-DG-019).
func (u SiteAddress) Diff(other SiteAddress) SiteAddressDelta { return DiffSiteAddress(u, other) }

// CalibrationDataDelta is the Delta companion type for delta.nested fields of
// type CalibrationData. It is generated by delta-gen and must not be edited.
type CalibrationDataDelta struct {
	// OffsetKPa: source CalibrationData.OffsetKPa (float32) — atomic replace; nil = no change.
	SetOffsetKPa *float32
	// LastCalibAt: source CalibrationData.LastCalibAt (time.Time) — atomic replace; nil = no change.
	SetLastCalibAt *time.Time
}

// ApplyCalibrationData produces the CalibrationData that results from applying d to u.
// It is a pure function with no chain-envelope validation (delta-gen spec §4.3).
func ApplyCalibrationData(u CalibrationData, d CalibrationDataDelta) CalibrationData {
	result := u
	if d.SetOffsetKPa != nil {
		result.OffsetKPa = *d.SetOffsetKPa
	} else {
		result.OffsetKPa = u.OffsetKPa
	}
	if d.SetLastCalibAt != nil {
		result.LastCalibAt = *d.SetLastCalibAt
	} else {
		result.LastCalibAt = u.LastCalibAt
	}
	return result
}

// Apply is an ergonomic same-package wrapper (R-DG-012, R-DG-013, R-DG-019).
func (u CalibrationData) Apply(d CalibrationDataDelta) CalibrationData {
	return ApplyCalibrationData(u, d)
}

// DiffCalibrationData produces the minimal CalibrationDataDelta such that ApplyCalibrationData(a, d)
// payload-equals b. Pure function, no chain-envelope validation (delta-gen spec §4.3).
func DiffCalibrationData(a, b CalibrationData) CalibrationDataDelta {
	d := CalibrationDataDelta{}
	if a.OffsetKPa != b.OffsetKPa {
		d.SetOffsetKPa = &b.OffsetKPa
	}
	if a.LastCalibAt != b.LastCalibAt {
		d.SetLastCalibAt = &b.LastCalibAt
	}
	return d
}

// Diff is an ergonomic same-package wrapper (R-DG-012, R-DG-013, R-DG-019).
func (u CalibrationData) Diff(other CalibrationData) CalibrationDataDelta {
	return DiffCalibrationData(u, other)
}

// PumpSnapshotDelta is the Delta companion type for PumpSnapshot.
// Each payload field is expressed as an optional pointer: a nil value means
// "no change" for that field when Apply is called.
type PumpSnapshotDelta struct {
	// Header: chain-lifecycle envelope (ChainID, Sequence, Provenance).
	runtime.Header
	// PressureKPa: source PumpSnapshot.PressureKPa (float32) — atomic replace; nil = no change.
	SetPressureKPa *float32
	// TempCelsius: source PumpSnapshot.TempCelsius (float32) — atomic replace; nil = no change.
	SetTempCelsius *float32
	// Location: source PumpSnapshot.Location (SiteAddress) — compositional delta; recursive Apply.
	Location SiteAddressDelta
	// Calibration: source PumpSnapshot.Calibration (CalibrationData) — tri-state envelope (OpIgnore / OpAssert / OpRetract); inner Apply via ApplyCalibrationData.
	Calibration runtime.FieldDelta[CalibrationDataDelta]
}

// Apply produces the Snapshot that results from applying d to s.
// It is a pure function; chain-envelope validations live in
// runtime.HeaderAfterApply and are propagated to the caller as a
// non-nil error. See delta-gen-spec.md §6.4 / §7.1 (Errata R-DG-012).
func Apply(s PumpSnapshot, d PumpSnapshotDelta) (PumpSnapshot, error) {
	var result PumpSnapshot
	hdr, err := runtime.HeaderAfterApply(s.Header, d.Header)
	if err != nil {
		return result, err
	}
	result.Header = hdr
	result.SerialNumber = s.SerialNumber
	if d.SetPressureKPa != nil {
		result.PressureKPa = *d.SetPressureKPa
	} else {
		result.PressureKPa = s.PressureKPa
	}
	if d.SetTempCelsius != nil {
		result.TempCelsius = *d.SetTempCelsius
	} else {
		result.TempCelsius = s.TempCelsius
	}
	result.Location = s.Location.Apply(d.Location)
	switch d.Calibration.Op {
	case runtime.OpRetract:
		result.Calibration = CalibrationData{}
	case runtime.OpAssert:
		result.Calibration = ApplyCalibrationData(s.Calibration, d.Calibration.Value)
	default:
		result.Calibration = s.Calibration
	}
	result.FirmwareVer = s.FirmwareVer
	return result, nil
}

// Apply is an ergonomic same-package wrapper that delegates to the
// package-level Apply function (R-DG-012, R-DG-013, R-DG-019).
func (s PumpSnapshot) Apply(d PumpSnapshotDelta) (PumpSnapshot, error) {
	return Apply(s, d)
}

// Diff produces the minimal Delta d such that Apply(a, d) payload-equals b.
// It is a pure function; chain-envelope validations live in
// runtime.HeaderForDiff and are propagated to the caller as a non-nil error.
// See delta-gen-spec.md §6.5 / §7.2 (Errata R-DG-012).
func Diff(a, b PumpSnapshot) (PumpSnapshotDelta, error) {
	hdr, err := runtime.HeaderForDiff(a.Header, b.Header)
	if err != nil {
		return PumpSnapshotDelta{}, err
	}
	d := PumpSnapshotDelta{Header: hdr}
	if a.PressureKPa != b.PressureKPa {
		d.SetPressureKPa = &b.PressureKPa
	}
	if a.TempCelsius != b.TempCelsius {
		d.SetTempCelsius = &b.TempCelsius
	}
	d.Location = a.Location.Diff(b.Location)
	if a.Calibration != b.Calibration {
		if b.Calibration == (CalibrationData{}) {
			d.Calibration = runtime.FieldDelta[CalibrationDataDelta]{Op: runtime.OpRetract}
		} else {
			d.Calibration = runtime.FieldDelta[CalibrationDataDelta]{Op: runtime.OpAssert, Value: DiffCalibrationData(a.Calibration, b.Calibration)}
		}
	}
	return d, nil
}

// Diff is an ergonomic same-package wrapper that delegates to the
// package-level Diff function (R-DG-012, R-DG-013, R-DG-019).
func (a PumpSnapshot) Diff(b PumpSnapshot) (PumpSnapshotDelta, error) {
	return Diff(a, b)
}

// Coalesce folds a slice of TDeltas into s by iterated Apply. It is a pure
// function; chain-envelope validations propagate from the first failing Apply
// step. An empty slice returns (s, nil) without any runtime call. See
// delta-gen-spec.md §7.3 / §8.3 (Errata R-DG-012, R-DG-012).
func Coalesce(s PumpSnapshot, ds []PumpSnapshotDelta) (PumpSnapshot, error) {
	result := s
	for _, d := range ds {
		var err error
		result, err = Apply(result, d)
		if err != nil {
			return PumpSnapshot{}, err
		}
	}
	return result, nil
}

// Coalesce is an ergonomic same-package wrapper that delegates to the
// package-level Coalesce function (R-DG-012, R-DG-013, R-DG-019).
func (s PumpSnapshot) Coalesce(ds []PumpSnapshotDelta) (PumpSnapshot, error) {
	return Coalesce(s, ds)
}

// EntityID creates a hash for the key field: SerialNumber
//
// It returns the deterministic content-hash EntityID of k. The hash is
// Blake2b-256 over the canonical encoding of k's fields (R-DG-034, R-DG-035, RT-02). It is
// a pure function: same input → same output forever.
func EntityID(k string) runtime.EntityID {
	h := runtime.NewHash()
	runtime.WriteString(h, k)
	return runtime.Finalise(h)
}
