#!/usr/bin/env python3
"""Unit tests for markdown-toc.py.

Exercises the TOC regenerator against synthesised markdown fixtures.
Checks:

* R01: inserts a delimited TOC block immediately before the first ##
  heading in a document that has none.
* R02: replaces an existing TOC block in place (idempotent on re-run).
* R03: the second invocation on identical content is a byte-level
  no-op — the file's bytes are unchanged.
* R04: the second invocation preserves the file's mtime (no-op-if-
  unchanged guard). This is the behaviour that makes the script safe
  to wire into build dependency chains.
* R05: ## and ### headings inside fenced code blocks are ignored.
* R06: both ## and ### headings are captured, with ### entries
  indented two spaces.
* R07: anchors are GitHub-compatible — lowercased, punctuation
  stripped, whitespace collapsed to hyphens.
* R08: exits non-zero when the document has no ## headings.
* R09: preserves all content outside the TOC block (preamble, body,
  trailing material) byte-for-byte.
* R10: heading lines carrying a refs-linkify-injected `<a id="…"></a>`
  anchor produce clean TOC link text and a GitHub-compatible slug —
  the raw HTML must not appear in either the link text or the anchor.

Run from the repo root or this directory:

    python3 designs/scripts/tests/test_markdown_toc.py

Exits 0 on success, non-zero on any failed assertion.
"""

from __future__ import annotations

import os
import subprocess
import sys
import tempfile
import time
from pathlib import Path


HERE = Path(__file__).resolve().parent
SCRIPTS = HERE.parent
MD_TOC = SCRIPTS / "markdown-toc.py"


def _fail(msg: str) -> None:
    print(f"FAIL: {msg}", file=sys.stderr)
    sys.exit(1)


def _ok(msg: str) -> None:
    print(f"ok   {msg}")


def _run(path: Path) -> subprocess.CompletedProcess:
    """Invoke markdown-toc.py against `path`; return the completed process."""
    return subprocess.run(
        ["python3", str(MD_TOC), str(path)],
        capture_output=True,
        text=True,
    )


def _mktemp_md(suffix: str = ".md") -> Path:
    """Create a tempfile under SCRIPTS so snap-confined interpreters can see it."""
    fd, name = tempfile.mkstemp(suffix=suffix, dir=str(SCRIPTS))
    os.close(fd)
    return Path(name)


# ----------------------------------------------------------------------
# Fixtures
# ----------------------------------------------------------------------

SIMPLE_DOC = """\
# Title

Preamble paragraph.

---

## Section One

Body of section one.

### Subsection 1.1

Deeper content.

## Section Two

Body of section two.
"""

# Fenced-code-block fixture — the ## and ### inside the fence must be ignored.
# Covers: R05
DOC_WITH_FENCE = """\
# Title

Preamble.

## Real Section

Some body.

```
## Fake Section (inside fence, must be ignored)
### Fake Subsection
```

## Another Real Section

More body.
"""

# Fixture that begins without any TOC block. Covers: R01 / R06 / R07.
DOC_FOR_INSERT = """\
# Document Title

Some preamble text here.

## First: Hello, World!

Body.

### Subsection — with punctuation!

More body.

## Second Section

End.
"""

# Fixture with refs-linkify-injected anchor tags in ## / ### headings.
# Covers: R10.
DOC_WITH_INJECTED_ANCHORS = """\
# Title

Preamble.

## Introduction

Body.

### <a id="r-eddt-001"></a>R-EDDT-001: Multiple Instrument Acquisition Modes

Requirement body.

### <a id="n-lake-003"></a>N-LAKE-003: Analytics Cost Management

Need body.

## Summary

End.
"""

# Fixture with no ## headings at all. Covers: R08.
DOC_NO_H2 = """\
# Only a Title

Some body text with no ## headings.

This file should trigger a non-zero exit.
"""


# ----------------------------------------------------------------------
# Tests
# ----------------------------------------------------------------------

def test_toc_inserted_before_first_h2() -> None:
    """Covers: R01, R06, R07 — TOC inserted with correct position and shape."""
    path = _mktemp_md()
    try:
        path.write_text(DOC_FOR_INSERT)
        res = _run(path)
        if res.returncode != 0:
            _fail(f"R01: script exited {res.returncode}; stderr={res.stderr!r}")
        content = path.read_text()

        toc_start = "<!-- TOC generated by scripts/markdown-toc.py -->"
        toc_end = "<!-- /TOC -->"
        if toc_start not in content or toc_end not in content:
            _fail("R01: TOC delimiters missing after insertion")

        # The TOC block must appear before the first ## heading.
        toc_pos = content.find(toc_start)
        first_h2_pos = content.find("\n## First:")
        if not (toc_pos < first_h2_pos):
            _fail("R01: TOC block not positioned before the first ## heading")

        # R06: both ## and ### entries present, with ### indented.
        toc_block = content[toc_pos : content.find(toc_end)]
        if "- [First: Hello, World!]" not in toc_block:
            _fail("R06: top-level ## heading missing from TOC")
        if "  - [Subsection" not in toc_block:
            _fail("R06: ### heading not indented in TOC")

        # R07: anchor is lowercased, punctuation stripped, spaces hyphenated.
        if "(#first-hello-world)" not in toc_block:
            _fail("R07: anchor not GitHub-compatible for 'First: Hello, World!'")

    finally:
        path.unlink()


def test_toc_replaces_existing_block() -> None:
    """Covers: R02 — running against a doc that already has a TOC
    replaces the block in place rather than appending a second one."""
    path = _mktemp_md()
    try:
        path.write_text(SIMPLE_DOC)
        # First run inserts the TOC.
        if _run(path).returncode != 0:
            _fail("R02: first run failed")

        after_first = path.read_text()
        toc_count_first = after_first.count(
            "<!-- TOC generated by scripts/markdown-toc.py -->"
        )
        if toc_count_first != 1:
            _fail(f"R02: first run produced {toc_count_first} TOC blocks, expected 1")

        # Second run on identical content must still produce exactly one block
        # (no accumulation).
        if _run(path).returncode != 0:
            _fail("R02: second run failed")
        after_second = path.read_text()
        toc_count_second = after_second.count(
            "<!-- TOC generated by scripts/markdown-toc.py -->"
        )
        if toc_count_second != 1:
            _fail(f"R02: second run produced {toc_count_second} TOC blocks, expected 1")

    finally:
        path.unlink()


def test_idempotent_bytes_on_repeat() -> None:
    """Covers: R03 — second invocation produces byte-identical output."""
    path = _mktemp_md()
    try:
        path.write_text(SIMPLE_DOC)
        _run(path)  # seed
        first = path.read_text()
        _run(path)  # should no-op
        second = path.read_text()
        if first != second:
            _fail("R03: second run changed the file's bytes")
    finally:
        path.unlink()


def test_mtime_preserved_on_noop() -> None:
    """Covers: R04 — when the committed TOC is already up-to-date,
    the script must not bump the file's mtime. This is the guarantee
    that makes the script safe to wire into Makefile dependency chains."""
    path = _mktemp_md()
    try:
        path.write_text(SIMPLE_DOC)
        _run(path)  # seed the TOC

        # Anchor the mtime well into the past so any rewrite is
        # unambiguously detectable.
        past = time.time() - 3600
        os.utime(path, (past, past))
        mtime_before = path.stat().st_mtime

        res = _run(path)
        if res.returncode != 0:
            _fail(f"R04: no-op run exited {res.returncode}")
        if "no changes" not in res.stdout:
            _fail(f"R04: expected 'no changes' log line; got {res.stdout!r}")

        mtime_after = path.stat().st_mtime
        if mtime_after != mtime_before:
            _fail(
                f"R04: mtime changed despite no-op "
                f"(before={mtime_before}, after={mtime_after})"
            )
    finally:
        path.unlink()


def test_fenced_headings_ignored() -> None:
    """Covers: R05 — ## / ### inside fenced code blocks are not
    treated as headings."""
    path = _mktemp_md()
    try:
        path.write_text(DOC_WITH_FENCE)
        if _run(path).returncode != 0:
            _fail("R05: script failed on fenced-content fixture")
        content = path.read_text()
        toc_start = "<!-- TOC generated by scripts/markdown-toc.py -->"
        toc_end = "<!-- /TOC -->"
        toc_block = content[content.find(toc_start) : content.find(toc_end)]
        if "Fake Section" in toc_block or "Fake Subsection" in toc_block:
            _fail("R05: headings inside fenced code block leaked into TOC")
        if "Real Section" not in toc_block:
            _fail("R05: real ## heading missing from TOC")
    finally:
        path.unlink()


def test_errors_on_no_h2() -> None:
    """Covers: R08 — exits non-zero when the document has no ## headings."""
    path = _mktemp_md()
    try:
        path.write_text(DOC_NO_H2)
        res = _run(path)
        if res.returncode == 0:
            _fail("R08: expected non-zero exit on a doc with no ## headings")
    finally:
        path.unlink()


def test_preserves_outside_content() -> None:
    """Covers: R09 — content outside the inserted/replaced TOC block
    is preserved byte-for-byte."""
    path = _mktemp_md()
    try:
        path.write_text(SIMPLE_DOC)
        _run(path)  # insert TOC
        content = path.read_text()

        toc_start = "<!-- TOC generated by scripts/markdown-toc.py -->"
        toc_end = "<!-- /TOC -->"

        # Rebuild the "without TOC" view from the result and compare to
        # the original. Expect byte-identity (modulo leading/trailing
        # whitespace normalisation around the TOC block).
        start = content.find(toc_start)
        end = content.find(toc_end) + len(toc_end)
        outside = (content[:start].rstrip() + "\n\n" + content[end:].lstrip("\n"))

        # SIMPLE_DOC preamble ends with the --- separator followed by a blank
        # line, then the first ##. When the TOC is removed, the structure
        # should round-trip to approximately the original layout.
        if "Preamble paragraph." not in outside:
            _fail("R09: preamble text not preserved")
        if "Body of section one." not in outside:
            _fail("R09: body text not preserved")
        if "Body of section two." not in outside:
            _fail("R09: trailing body text not preserved")

    finally:
        path.unlink()


def test_injected_anchor_stripped_from_toc() -> None:
    """Covers: R10 — heading lines with a refs-linkify-injected
    `<a id="…"></a>` anchor produce clean TOC link text and a
    GitHub-compatible slug; raw HTML must not appear in either."""
    path = _mktemp_md()
    try:
        path.write_text(DOC_WITH_INJECTED_ANCHORS)
        res = _run(path)
        if res.returncode != 0:
            _fail(f"R10: script exited {res.returncode}; stderr={res.stderr!r}")
        content = path.read_text()

        toc_start = "<!-- TOC generated by scripts/markdown-toc.py -->"
        toc_end = "<!-- /TOC -->"
        toc_block = content[content.find(toc_start) : content.find(toc_end)]

        # Link text must be clean (no raw HTML).
        if "<a id=" in toc_block:
            _fail("R10: raw '<a id=' HTML leaked into TOC link text or anchor")

        # The broken '#a-id' pattern (slug of raw HTML) must not appear.
        if "(#a-id" in toc_block:
            _fail("R10: broken '#a-id' anchor slug found in TOC")

        # Correct link text and GitHub-compatible slug for each identifier heading.
        if "- [R-EDDT-001: Multiple Instrument Acquisition Modes]" not in toc_block:
            _fail("R10: clean link text for R-EDDT-001 missing from TOC")
        if "(#r-eddt-001-multiple-instrument-acquisition-modes)" not in toc_block:
            _fail("R10: clean anchor for R-EDDT-001 missing from TOC")

        if "- [N-LAKE-003: Analytics Cost Management]" not in toc_block:
            _fail("R10: clean link text for N-LAKE-003 missing from TOC")
        if "(#n-lake-003-analytics-cost-management)" not in toc_block:
            _fail("R10: clean anchor for N-LAKE-003 missing from TOC")

    finally:
        path.unlink()


def main() -> None:
    tests = [
        ("R01/R06/R07 — TOC inserted with correct position and shape",
         test_toc_inserted_before_first_h2),
        ("R02 — existing TOC replaced, never accumulated",
         test_toc_replaces_existing_block),
        ("R03 — second run is byte-identical",
         test_idempotent_bytes_on_repeat),
        ("R04 — mtime preserved when TOC is already up-to-date",
         test_mtime_preserved_on_noop),
        ("R05 — headings inside fenced code blocks are ignored",
         test_fenced_headings_ignored),
        ("R08 — non-zero exit on documents with no ## headings",
         test_errors_on_no_h2),
        ("R09 — non-TOC content preserved through insertion",
         test_preserves_outside_content),
        ("R10 — injected refs-linkify anchors stripped from TOC link text and slug",
         test_injected_anchor_stripped_from_toc),
    ]
    for label, fn in tests:
        fn()
        _ok(label)
    print("\nall tests passed")


if __name__ == "__main__":
    main()
