#!/usr/bin/env python3
"""Unit tests for markdown-index.py.

This script had zero existing test coverage before this file. Exercises
the alphabetical-index regenerator against synthesised markdown fixtures.
Checks:

* R01: terms are correctly paired with their most recent `## N.` section.
* R02: generated index entries are sorted alphabetically (case-insensitive).
* R03: an existing index block is replaced in place on re-run, not
  duplicated or appended.
* R04: generated entries use the documented reference-link + anchor shape.
* R05: content after the index block (e.g. a reference-links block
  appended by other tooling) is preserved.
* R06: exits non-zero when no ### headings are found.
* R07: second run on already-current content reproduces byte-identical
  output.
* R08: a ## N. Section / ### Term pair inside a fenced code block is not
  picked up as a real entry.
* R09: a ## N. Section / ### Term pair inside an HTML comment is not
  picked up as a real entry, while real entries before and after the
  comment are indexed correctly.
* R10: a same-line, self-closing comment does not block extraction of a
  real entry that follows it.
* R11: a legacy index block with no end marker is treated as extending
  to EOF when locating the existing block, and is fully replaced on
  regeneration.
* R12: in a document that also carries a TOC block and a Reference-links
  block (mirroring eddt-stakeholders.md's real shape), regenerating the
  index touches only the index block — the other two blocks pass
  through byte-for-byte unchanged.
* R13: when the committed index is already up-to-date, the script does
  not rewrite the file — mtime is preserved. This is a newly-added
  guarantee (this script previously always wrote unconditionally),
  matching markdown-toc.py/markdown-num.py's existing contract.

Run from the repo root or this directory:

    python3 designs/scripts/tests/test_markdown_index.py

Exits 0 on success, non-zero on any failed assertion.
"""

from __future__ import annotations

import os
import subprocess
import sys
import tempfile
import time
from pathlib import Path


HERE = Path(__file__).resolve().parent
SCRIPTS = HERE.parent
MD_INDEX = SCRIPTS / "markdown-index.py"


def _fail(msg: str) -> None:
    print(f"FAIL: {msg}", file=sys.stderr)
    sys.exit(1)


def _ok(msg: str) -> None:
    print(f"ok   {msg}")


def _run(path: Path) -> subprocess.CompletedProcess:
    """Invoke markdown-index.py against `path`; return the completed process."""
    return subprocess.run(
        ["python3", str(MD_INDEX), str(path)],
        capture_output=True,
        text=True,
    )


def _mktemp_md(suffix: str = ".md") -> Path:
    """Create a tempfile under SCRIPTS so snap-confined interpreters can see it."""
    fd, name = tempfile.mkstemp(suffix=suffix, dir=str(SCRIPTS))
    os.close(fd)
    return Path(name)


# ----------------------------------------------------------------------
# Fixtures
# ----------------------------------------------------------------------

# Basic glossary, no existing index. Covers: R01, R04.
DOC_SIMPLE = """\
# Glossary

## 1. General Terms

### Alpha

Definition of alpha.

### Beta

Definition of beta.

## 2. Advanced Terms

### Gamma

Definition of gamma.
"""

# Deliberately scrambled term order to prove alphabetical sorting. Covers: R02.
DOC_UNSORTED = """\
# Glossary

## 1. Terms

### Zeta

Def.

### Alpha

Def.

### Mid

Def.
"""

# Already has a valid index block with a stale entry set (missing "Beta",
# which is now present in the body). Covers: R03.
DOC_WITH_EXISTING_INDEX = """\
# Glossary

## 1. Terms

### Alpha

Def.

### Beta

Def.

---

## Alphabetical Index

<!-- Generated by scripts/markdown-index.py — re-run after adding or renaming entries. -->

- [Alpha][alpha] -- Terms

[alpha]: #alpha "Alpha"

<!-- /Alphabetical Index -->
"""

# Existing index block followed by trailing content from other tooling
# (simulating a refs-linkify reference-links block). Covers: R05.
DOC_WITH_TRAILING_CONTENT = """\
# Glossary

## 1. Terms

### Alpha

Def.

---

## Alphabetical Index

<!-- Generated by scripts/markdown-index.py — re-run after adding or renaming entries. -->

- [Alpha][alpha] -- Terms

[alpha]: #alpha "Alpha"

<!-- /Alphabetical Index -->

<!-- Reference links generated by scripts/refs-linkify.py -->

[d-01]: reify-refinements.md#d-01

<!-- /Reference links -->
"""

# No ### headings at all. Covers: R06.
DOC_NO_TERMS = """\
# Glossary

## 1. Terms

Just a section, no entries.
"""

# ## / ### -shaped lines inside a fenced code block. Covers: R08.
DOC_WITH_FENCE = """\
# Glossary

## 1. Real Section

### Real Term

Def.

```
## 9. Fake Section (inside fence, must be ignored)
### Fake Term (also inside fence)
```

### Another Real Term

Def.
"""

# ## / ### -shaped lines inside a leading HTML comment. Covers: R09.
DOC_WITH_COMMENT = """\
# Glossary

## 1. Real Section

### Real Term

Def.

<!--

## 9. Fake Section (inside comment, must be ignored)

### Fake Term (also inside comment)

-->

### Another Real Term

Def.
"""

# Same-line, self-closing comment immediately followed by a real entry.
# Covers: R10.
DOC_WITH_SAME_LINE_COMMENT = """\
# Glossary

<!-- a short note -->

## 1. Real Section

### Real Term

Def.
"""

# Legacy index block: heading present, but no end marker. Covers: R11.
DOC_WITH_LEGACY_INDEX = """\
# Glossary

## 1. Terms

### Alpha

Def.

### Beta

Def.

---

## Alphabetical Index

- [OldEntry][oldentry] -- Terms

[oldentry]: #oldentry "OldEntry"
"""

# Mirrors the real shape of eddt-stakeholders.md: a document carrying a
# TOC block and a Reference-links block alongside the Alphabetical Index
# block. Covers: R12.
DOC_WITH_OTHER_GENERATED_BLOCKS = """\
# Glossary

<!-- TOC generated by scripts/markdown-toc.py -->

- [1. Terms](#1-terms)

<!-- /TOC -->

## 1. Terms

### Alpha

Def.

### Beta

Def.

---

## Alphabetical Index

<!-- Generated by scripts/markdown-index.py — re-run after adding or renaming entries. -->

- [Alpha][alpha] -- Terms

[alpha]: #alpha "Alpha"

<!-- /Alphabetical Index -->

<!-- Reference links generated by scripts/refs-linkify.py -->

[d-01]: reify-refinements.md#d-01

<!-- /Reference links -->
"""


# ----------------------------------------------------------------------
# Tests
# ----------------------------------------------------------------------

def test_terms_paired_with_correct_section() -> None:
    """Covers: R01 — terms are paired with their most recent ## N. section."""
    path = _mktemp_md()
    try:
        path.write_text(DOC_SIMPLE)
        res = _run(path)
        if res.returncode != 0:
            _fail(f"R01: script exited {res.returncode}; stderr={res.stderr!r}")
        content = path.read_text()
        if "- [Alpha][alpha] -- General Terms" not in content:
            _fail("R01: Alpha not paired with 'General Terms'")
        if "- [Beta][beta] -- General Terms" not in content:
            _fail("R01: Beta not paired with 'General Terms'")
        if "- [Gamma][gamma] -- Advanced Terms" not in content:
            _fail("R01: Gamma not paired with 'Advanced Terms'")
    finally:
        path.unlink()


def test_entries_sorted_alphabetically() -> None:
    """Covers: R02 — generated index entries are sorted alphabetically,
    regardless of their order of appearance in the body."""
    path = _mktemp_md()
    try:
        path.write_text(DOC_UNSORTED)
        res = _run(path)
        if res.returncode != 0:
            _fail(f"R02: script exited {res.returncode}; stderr={res.stderr!r}")
        content = path.read_text()
        pos_alpha = content.find("- [Alpha]")
        pos_mid = content.find("- [Mid]")
        pos_zeta = content.find("- [Zeta]")
        if not (pos_alpha < pos_mid < pos_zeta):
            _fail(f"R02: entries not sorted alphabetically: {pos_alpha=}, {pos_mid=}, {pos_zeta=}")
    finally:
        path.unlink()


def test_existing_index_replaced_in_place() -> None:
    """Covers: R03 — an existing index block is replaced, not duplicated
    or appended."""
    path = _mktemp_md()
    try:
        path.write_text(DOC_WITH_EXISTING_INDEX)
        res = _run(path)
        if res.returncode != 0:
            _fail(f"R03: script exited {res.returncode}; stderr={res.stderr!r}")
        content = path.read_text()
        if content.count("## Alphabetical Index") != 1:
            _fail(f"R03: expected exactly 1 index heading, found {content.count('## Alphabetical Index')}")
        if "- [Beta][beta] -- Terms" not in content:
            _fail("R03: newly-added Beta term missing from regenerated index")
    finally:
        path.unlink()


def test_entry_shape_reference_link_and_anchor() -> None:
    """Covers: R04 — generated entries use the documented reference-link
    + anchor shape."""
    path = _mktemp_md()
    try:
        path.write_text(DOC_SIMPLE)
        res = _run(path)
        if res.returncode != 0:
            _fail(f"R04: script exited {res.returncode}; stderr={res.stderr!r}")
        content = path.read_text()
        if "- [Alpha][alpha] -- General Terms" not in content:
            _fail("R04: entry line does not match documented shape")
        if '[alpha]: #alpha "Alpha"' not in content:
            _fail("R04: reference-definition line does not match documented shape")
    finally:
        path.unlink()


def test_content_after_index_preserved() -> None:
    """Covers: R05 — content after the index block (e.g. a
    reference-links block appended by other tooling) is preserved."""
    path = _mktemp_md()
    try:
        path.write_text(DOC_WITH_TRAILING_CONTENT)
        res = _run(path)
        if res.returncode != 0:
            _fail(f"R05: script exited {res.returncode}; stderr={res.stderr!r}")
        content = path.read_text()
        if "<!-- Reference links generated by scripts/refs-linkify.py -->" not in content:
            _fail("R05: trailing reference-links block start marker missing")
        if "[d-01]: reify-refinements.md#d-01" not in content:
            _fail("R05: trailing reference-links block content missing")
        if "<!-- /Reference links -->" not in content:
            _fail("R05: trailing reference-links block end marker missing")
    finally:
        path.unlink()


def test_errors_on_no_terms() -> None:
    """Covers: R06 — exits non-zero when no ### headings are found."""
    path = _mktemp_md()
    try:
        path.write_text(DOC_NO_TERMS)
        res = _run(path)
        if res.returncode == 0:
            _fail("R06: expected non-zero exit on a doc with no ### headings")
    finally:
        path.unlink()


def test_second_run_byte_identical() -> None:
    """Covers: R07 — a second run on already-current content reproduces
    byte-identical output."""
    path = _mktemp_md()
    try:
        path.write_text(DOC_SIMPLE)
        _run(path)
        first = path.read_text()
        _run(path)
        second = path.read_text()
        if first != second:
            _fail("R07: second run changed the file's bytes")
    finally:
        path.unlink()


def test_mtime_preserved_on_noop() -> None:
    """Covers: R13 — when the committed index is already up-to-date,
    the script must not bump the file's mtime. Newly-added guarantee
    (this script previously always wrote unconditionally), matching
    markdown-toc.py/markdown-num.py's existing contract."""
    path = _mktemp_md()
    try:
        path.write_text(DOC_SIMPLE)
        _run(path)  # seed the index

        past = time.time() - 3600
        os.utime(path, (past, past))
        mtime_before = path.stat().st_mtime

        res = _run(path)
        if res.returncode != 0:
            _fail(f"R13: no-op run exited {res.returncode}")
        if "no changes" not in res.stdout:
            _fail(f"R13: expected 'no changes' log line; got {res.stdout!r}")

        mtime_after = path.stat().st_mtime
        if mtime_after != mtime_before:
            _fail(
                f"R13: mtime changed despite no-op "
                f"(before={mtime_before}, after={mtime_after})"
            )
    finally:
        path.unlink()


def test_fenced_headings_ignored() -> None:
    """Covers: R08 — ## / ### -shaped lines inside a fenced code block
    are not picked up as real entries."""
    path = _mktemp_md()
    try:
        path.write_text(DOC_WITH_FENCE)
        res = _run(path)
        if res.returncode != 0:
            _fail(f"R08: script exited {res.returncode}; stderr={res.stderr!r}")
        content = path.read_text()
        index_block = content[content.find("## Alphabetical Index"):]
        if "Fake Term" in index_block or "Fake Section" in index_block:
            _fail("R08: fenced heading leaked into the generated index")
        if "Real Term" not in index_block:
            _fail("R08: real term missing from the generated index")
        if "Another Real Term" not in index_block:
            _fail("R08: real term after the fence missing from the generated index")
    finally:
        path.unlink()


def test_commented_headings_ignored() -> None:
    """Covers: R09 — ## / ### -shaped lines inside an HTML comment are
    not picked up as real entries; real entries before and after the
    comment are indexed correctly."""
    path = _mktemp_md()
    try:
        path.write_text(DOC_WITH_COMMENT)
        res = _run(path)
        if res.returncode != 0:
            _fail(f"R09: script exited {res.returncode}; stderr={res.stderr!r}")
        content = path.read_text()
        index_block = content[content.find("## Alphabetical Index"):]
        if "Fake Term" in index_block or "Fake Section" in index_block:
            _fail("R09: commented-out heading leaked into the generated index")
        if "Real Term" not in index_block:
            _fail("R09: real term before the comment missing from the generated index")
        if "Another Real Term" not in index_block:
            _fail("R09: real term after the comment missing from the generated index")
    finally:
        path.unlink()


def test_same_line_comment_does_not_block_extraction() -> None:
    """Covers: R10 — a same-line, self-closing comment does not suppress
    extraction of a real entry that follows it."""
    path = _mktemp_md()
    try:
        path.write_text(DOC_WITH_SAME_LINE_COMMENT)
        res = _run(path)
        if res.returncode != 0:
            _fail(f"R10: script exited {res.returncode}; stderr={res.stderr!r}")
        content = path.read_text()
        index_block = content[content.find("## Alphabetical Index"):]
        if "Real Term" not in index_block:
            _fail("R10: entry after same-line comment missing from the generated index")
    finally:
        path.unlink()


def test_legacy_index_no_end_marker() -> None:
    """Covers: R11 — a legacy index block with no end marker is treated
    as extending to EOF when locating the existing block, and is fully
    replaced (not duplicated alongside the stale legacy content) on
    regeneration."""
    path = _mktemp_md()
    try:
        path.write_text(DOC_WITH_LEGACY_INDEX)
        res = _run(path)
        if res.returncode != 0:
            _fail(f"R11: script exited {res.returncode}; stderr={res.stderr!r}")
        content = path.read_text()
        if content.count("## Alphabetical Index") != 1:
            _fail(f"R11: expected exactly 1 index heading, found {content.count('## Alphabetical Index')}")
        if "OldEntry" in content:
            _fail("R11: stale legacy entry was not replaced")
        if "- [Alpha][alpha] -- Terms" not in content:
            _fail("R11: Alpha term missing from regenerated index")
        if "- [Beta][beta] -- Terms" not in content:
            _fail("R11: Beta term missing from regenerated index")
        if "<!-- /Alphabetical Index -->" not in content:
            _fail("R11: regenerated index missing its end marker")
    finally:
        path.unlink()


def test_other_generated_blocks_untouched() -> None:
    """Covers: R12 — in a document that also carries a TOC block and a
    Reference-links block (mirroring eddt-stakeholders.md's real
    shape), regenerating the index touches only the index block. Guards
    the strip_marked_block unification: the three generated-block types
    must keep mutually distinct markers and never corrupt or consume
    each other's content."""
    path = _mktemp_md()
    try:
        path.write_text(DOC_WITH_OTHER_GENERATED_BLOCKS)
        toc_block_before = DOC_WITH_OTHER_GENERATED_BLOCKS[
            DOC_WITH_OTHER_GENERATED_BLOCKS.find("<!-- TOC generated") :
            DOC_WITH_OTHER_GENERATED_BLOCKS.find("<!-- /TOC -->") + len("<!-- /TOC -->")
        ]
        refs_block_before = DOC_WITH_OTHER_GENERATED_BLOCKS[
            DOC_WITH_OTHER_GENERATED_BLOCKS.find("<!-- Reference links generated") :
        ]

        res = _run(path)
        if res.returncode != 0:
            _fail(f"R12: script exited {res.returncode}; stderr={res.stderr!r}")
        content = path.read_text()

        if toc_block_before not in content:
            _fail("R12: TOC block was altered")
        if refs_block_before not in content:
            _fail("R12: Reference-links block was altered")
        index_block = content[content.find("## Alphabetical Index"):content.find("<!-- Reference links")]
        if "- [Alpha][alpha] -- Terms" not in index_block:
            _fail("R12: regenerated index missing a real entry")
    finally:
        path.unlink()


def main() -> None:
    tests = [
        ("R01 — terms paired with their most recent section",
         test_terms_paired_with_correct_section),
        ("R02 — entries sorted alphabetically",
         test_entries_sorted_alphabetically),
        ("R03 — existing index block replaced in place",
         test_existing_index_replaced_in_place),
        ("R04 — entry shape matches documented reference-link + anchor form",
         test_entry_shape_reference_link_and_anchor),
        ("R05 — content after the index block is preserved",
         test_content_after_index_preserved),
        ("R06 — non-zero exit when no ### headings are found",
         test_errors_on_no_terms),
        ("R07 — second run reproduces byte-identical output",
         test_second_run_byte_identical),
        ("R08 — headings inside fenced code blocks are ignored",
         test_fenced_headings_ignored),
        ("R09 — headings inside HTML comments are ignored",
         test_commented_headings_ignored),
        ("R10 — same-line comment does not block extraction of following entry",
         test_same_line_comment_does_not_block_extraction),
        ("R11 — legacy index block with no end marker treated as extending to EOF",
         test_legacy_index_no_end_marker),
        ("R12 — TOC and Reference-links blocks untouched",
         test_other_generated_blocks_untouched),
        ("R13 — mtime preserved when index is already up-to-date",
         test_mtime_preserved_on_noop),
    ]
    for label, fn in tests:
        fn()
        _ok(label)
    print("\nall tests passed")


if __name__ == "__main__":
    main()
